// Actions du joueur (GAME_DESIGN §6, contrat §14). Données pures : aucune logique, aucun DOM.
// phase    : 'morning' | 'afternoon' | 'night'
// legality : 'legal' | 'grey' | 'illegal'
// cost     : { time } = créneaux d'après-midi (3 par après-midi) · { minutes } = minutes de jeu la nuit
// requires : conditions §14 (flags, notFlags, stats, hidden, day, chance) · effects : effets §14
// witnessed: { exposure 0–1, by: [témoins], effects } — effets appliqués seulement si quelqu'un a vu
// sim      : action déjà gérée nativement par la nuit 3D (src/sim) ; les `effects` ici sont des extras.
//            `simArgs` = paramètres passés tels quels à sim.act({ type: sim, ...simArgs }).
// once     : une seule fois par campagne · result : texte affiché après l'action
// Règle d'écriture : les actes illégaux restent au niveau du jeu (un libellé, une conséquence, une réplique).
// Jamais de mode d'emploi réel.

export const ACTIONS = [
  // ════════════════════════════════════════════════════════════════════════
  // NUIT — LÉGAL (déjà dans le moteur)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'night_photo',
    label: 'Photographier la terrasse (photo + relevé dB)',
    phase: 'night',
    legality: 'legal',
    sim: 'photo',
    cost: { minutes: 1 },
    effects: {},
    result: 'Clic. Horodatage, décibels, nombre de chaises. La photo rejoint le dossier, entre deux autres photos de chaises.',
  },
  {
    id: 'night_police',
    label: 'Appeler la police municipale',
    phase: 'night',
    legality: 'legal',
    sim: 'police',
    cost: { minutes: 2 },
    effects: {},
    result: "« Une équipe va passer, monsieur. » Le standardiste a dit « va passer » comme on dit « un jour, peut-être ».",
  },
  {
    id: 'night_ronde_jeremie',
    label: 'Faire la ronde de 22h avec Jérémie et Biloute',
    phase: 'night',
    legality: 'legal',
    cost: { minutes: 20 },
    requires: { stats: { asso: '>=30' } },
    effects: { setFlags: ['joined_rounds'], asso: +3, dossier: +1, sleep: -3 },
    result: "Jérémie compte les tables à voix haute, Biloute renifle chaque pied de chaise, vous notez. Biloute s’arrête net devant chaque table qui déborde et la fixe, comme un huissier. Personne ne sait comment il fait, mais il a raison.",
  },
  {
    id: 'night_police_asso',
    label: "Appeler la police « pour l’Association de la rue des Bouchers »",
    phase: 'night',
    legality: 'legal',
    sim: 'police',
    simArgs: { asso: true },
    cost: { minutes: 2 },
    effects: { hostility: +5 },
    result: "Le mot « Association » réveille le standard. Il réveille aussi l’estaminet : désormais, ils savent qui appelle.",
  },
  {
    id: 'night_ask_waiter',
    label: 'Demander poliment au serveur de rentrer les tables',
    phase: 'night',
    legality: 'legal',
    sim: 'waiter',
    cost: { minutes: 3 },
    requires: { notFlags: ['custody'] },
    effects: { setFlags: ['asked_waiter'] },
    result: "Le serveur regarde l’horloge, regarde Dédé, regarde ses chaussures. « Je vais voir ce que je peux faire, hein. »",
  },
  {
    id: 'night_whatsapp',
    label: 'Envoyer les photos sur le groupe WhatsApp',
    phase: 'night',
    legality: 'legal',
    sim: 'asso',
    cost: { minutes: 2 },
    effects: { setFlags: ['whatsapp_rally'] },
    result: "Trois coches bleues, dix-sept réactions, un GIF de Seb. Personne ne dort dans la rue, au moins on est solidaires.",
  },
  {
    id: 'night_mairie',
    label: 'Signaler à la mairie (formulaire en ligne)',
    phase: 'night',
    legality: 'legal',
    sim: 'mairie',
    cost: { minutes: 4 },
    effects: { setFlags: ['reported_mairie'] },
    result: "Votre signalement n°2026-08817 a bien été enregistré. Il sera traité dans l’ordre d’arrivée. Vous êtes probablement derrière les pigeons.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // NUIT — GRIS
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'night_camera_window',
    label: 'Installer une caméra à sa fenêtre',
    phase: 'night',
    legality: 'grey',
    once: true,
    cost: { minutes: 10 },
    requires: { notFlags: ['camera_window'] },
    effects: {
      setFlags: ['camera_window'],
      dossier: +2,
      evidence: { kind: 'camera', quality: 0.5, legal: false, label: 'Images en continu de la terrasse (caméra fenêtre)' },
    },
    witnessed: { exposure: 0.2, by: ['seb_nico', 'waiter', 'ghislain'], effects: { hostility: +10 } },
    result: "La caméra filme la rue jour et nuit. La CNIL n’aimerait pas ça, le tribunal n’en voudra pas, mais La Voix du Nordiste, elle, adorerait.",
  },
  {
    id: 'night_film_faces',
    label: 'Filmer les clients à visage découvert',
    phase: 'night',
    legality: 'grey',
    cost: { minutes: 3 },
    effects: {
      setFlags: ['filmed_faces'],
      dossier: +1,
      evidence: { kind: 'video', quality: 0.5, legal: false, label: 'Vidéo : tablée de neuf, visages compris' },
    },
    witnessed: { exposure: 0.5, by: ['customers', 'waiter', 'dede'], effects: { hostility: +10, risk: +5 } },
    result: "Un client lève son verre à la caméra. Un autre lève autre chose. Juridiquement, ni l’un ni l’autre n’a donné son accord.",
  },
  {
    id: 'night_flood_police',
    label: 'Rappeler la police… et rappeler… et rappeler',
    phase: 'night',
    legality: 'grey',
    cost: { minutes: 10 },
    requires: { flags: ['called_police'] },
    effects: { setFlags: ['police_flooded', 'serial_caller'], asso: -3, corruption: +5 },
    result: "Au septième appel, le standardiste vous appelle par votre prénom. Au huitième, il ne décroche plus. Bravo : vous êtes une légende du commissariat.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // NUIT — ILLÉGAL
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'night_bucket',
    label: "Vider un seau d’eau par la fenêtre",
    phase: 'night',
    legality: 'illegal',
    sim: 'bucket',
    cost: { minutes: 2 },
    effects: {},
    witnessed: { exposure: 0.6, by: ['klaas', 'seb_nico', 'waiter', 'customers'], effects: {} },
    result: "Splatch. La terrasse se lève d’un bloc, comme pour une ola. Une méthode ancestrale, déjà pratiquée dans cette rue en 1729.",
  },
  {
    id: 'night_camera_awning',
    label: "Cacher une caméra sous le store de l’estaminet",
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 15 },
    requires: { notFlags: ['camera_awning', 'camera_found'] },
    effects: {
      setFlags: ['camera_awning'],
      dossier: +3,
      evidence: { kind: 'camera', quality: 0.7, legal: false, label: "Caméra sous le store : la terrasse vue d’en haut, toute la nuit" },
    },
    witnessed: { exposure: 0.5, by: ['klaas', 'seb_nico', 'waiter', 'dede', 'ghislain', 'customers', 'biloute'], effects: { risk: +20 } },
    result: "Un petit œil noir entre deux franges du store. Il voit tout : les tables, les chaises, et Ghislain qui se recoiffe dans la vitrine.",
  },
  {
    id: 'night_borrow_power',
    label: "Brancher la caméra sur l’électricité de l’estaminet",
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 10 },
    requires: { flags: ['camera_awning'], notFlags: ['power_stolen', 'camera_found'] },
    effects: { setFlags: ['power_stolen'], dossier: +1 },
    witnessed: { exposure: 0.4, by: ['klaas', 'seb_nico', 'waiter', 'ghislain'], effects: { risk: +15 } },
    result: "La caméra ne tombera plus jamais en panne de batterie. L’estaminet paie désormais pour se faire filmer. Il y a une forme de justice là-dedans, que le Code pénal ne partage pas.",
  },
  {
    id: 'night_wifi',
    label: "Se connecter au wifi de l’estaminet",
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 20 },
    requires: { flags: ['proj_wifi_cracker'], notFlags: ['wifi_cracked'] },
    effects: { setFlags: ['wifi_cracked'], risk: +5 },
    result: "Le programme que vous avez fini seul tourne vingt minutes. Clode Kode, qui a refusé d’y toucher, vous envoie l’article 323-1 du Code pénal en PDF, avec un smiley inquiet. Le réseau « BERNADETTE_INVITES » vous accueille. Vous n’êtes pas invité.",
  },
  {
    id: 'night_cardboard_exhaust',
    label: "Scotcher un carton sur la sortie d’extraction",
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 8 },
    requires: { day: [2, 14], notFlags: ['exhaust_meeting_won'] },
    effects: { setFlags: ['cardboard_exhaust'], sleep: +10, hostility: +15 },
    witnessed: { exposure: 0.5, by: ['klaas', 'seb_nico', 'waiter', 'ghislain', 'biloute'], effects: { risk: +25, asso: -5 } },
    result: "Pour la première fois depuis des mois, ça ne sent pas la friture sous votre fenêtre. En bas, la cuisine ouvre toutes ses fenêtres et ça sent la friture partout ailleurs. Le lendemain, Ghislain fait le tour de la façade avec un mètre et un air de procès-verbal.",
  },
  {
    id: 'night_stink_bomb',
    label: 'Lâcher une boule puante sur la terrasse',
    phase: 'night',
    legality: 'illegal',
    cost: { minutes: 3 },
    effects: { setFlags: ['stink_bomb'], hostility: +10 },
    witnessed: { exposure: 0.45, by: ['klaas', 'seb_nico', 'waiter', 'customers', 'biloute'], effects: { risk: +12, asso: -3 } },
    result: "La terrasse se vide en quatre minutes. Un client accuse la carbonnade. Dédé accuse le canal d’avant 1912. Personne n’a de preuve : seulement des soupçons, et le nez qui pique.",
  },
  {
    id: 'night_saboter_cuisine',
    label: 'Saboter la cuisine (inverser le sel et le sucre)',
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 15 },
    requires: { flags: ['waiter_informant'], notFlags: ['kitchen_sabotaged'] },
    effects: { setFlags: ['kitchen_sabotaged'], hostility: +20 },
    witnessed: { exposure: 0.55, by: ['waiter', 'dede', 'ghislain'], effects: { risk: +35, setFlags: ['kitchen_sabotage_caught'] } },
    result: "Le service du soir est une catastrophe sucrée : frites au sucre glace, crème brûlée salée, carbonnade au goût de pain d’épices (ça, personne ne voit la différence). Les avis tombent comme une drache.",
  },
  {
    id: 'night_laxatif_carbonnade',
    label: 'Mettre un laxatif dans la carbonnade',
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 15 },
    requires: { flags: ['waiter_informant'], notFlags: ['laxative_done'] },
    effects: { setFlags: ['laxative_done'], hostility: +30, asso: -10 },
    witnessed: { exposure: 0.6, by: ['waiter', 'dede', 'ghislain'], effects: { risk: +60, asso: -15, setFlags: ['laxative_caught'] } },
    result: "Vers 21h40, la terrasse découvre la notion de file d’attente. Un seul WC, quatorze clients, un Dédé qui hurle « c’est pas la carbonnade, c’est le canal d’avant 1912 ! ». La terrasse est vide à 22h pile. Pour la première fois. Vous n’en êtes pas fier. Enfin, pas complètement.",
  },
  {
    id: 'night_sabotage_chairs',
    label: 'Dévisser les chaises de la terrasse',
    phase: 'night',
    legality: 'illegal',
    cost: { minutes: 12 },
    requires: { notFlags: ['sabotage_chairs'] },
    effects: { setFlags: ['sabotage_chairs'], hostility: +10 },
    witnessed: { exposure: 0.4, by: ['klaas', 'seb_nico', 'waiter', 'biloute'], effects: { risk: +15 } },
    result: "Demain, les chaises auront un léger tangage. La terrasse ressemblera à un ferry pour Douvres. Le mal de mer, c’est quand même mieux que le tapage.",
  },
  {
    id: 'night_sabotage_parasols',
    label: 'Faire disparaître les parasols',
    phase: 'night',
    legality: 'illegal',
    cost: { minutes: 10 },
    requires: { notFlags: ['sabotage_parasols'] },
    effects: { setFlags: ['sabotage_parasols'], hostility: +12 },
    witnessed: { exposure: 0.5, by: ['klaas', 'seb_nico', 'waiter', 'customers', 'biloute'], effects: { risk: +20, asso: -3 } },
    result: "Trois parasols en moins. Vous avez maintenant trois parasols dans votre salon et aucun endroit où les mettre. Le vol, c’est d’abord un problème de rangement.",
  },
  {
    id: 'night_sabotage_locks',
    label: 'Coller les cadenas de la terrasse',
    phase: 'night',
    legality: 'illegal',
    cost: { minutes: 5 },
    requires: { notFlags: ['sabotage_locks'] },
    effects: { setFlags: ['sabotage_locks'], hostility: +8 },
    witnessed: { exposure: 0.35, by: ['klaas', 'seb_nico', 'biloute'], effects: { risk: +12 } },
    result: "Demain midi, Dédé passera une heure à jurer sur un cadenas. Une heure sans terrasse. Une heure de paix, achetée au prix d’une dégradation de bien d’autrui.",
  },
  {
    id: 'night_bribe_waiter',
    label: 'Glisser un billet au serveur pour qu’il parle',
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 5 },
    requires: { flags: ['asked_waiter'], notFlags: ['waiter_bribed', 'waiter_fired'] },
    effects: { setFlags: ['waiter_bribed', 'met_waiter'] },
    witnessed: { exposure: 0.4, by: ['dede', 'ghislain', 'customers'], effects: { risk: +10, hostility: +15, setFlags: ['waiter_fired'] } },
    result: "Il empoche le billet sans le regarder. « Je m’appelle Théo. Je finis à minuit et demie. Et je vous ai jamais vu. »",
  },
  {
    id: 'night_backroom_photo',
    label: "Se cacher dans l’arrière-salle pour photographier le pot-de-vin",
    phase: 'night',
    legality: 'illegal',
    once: true,
    cost: { minutes: 30 },
    requires: { flags: ['waiter_informant', 'seen_complaisance'], notFlags: ['bribe_photo_illegal'] },
    effects: {
      setFlags: ['backroom_sneak', 'bribe_photo_illegal', 'corruption_proof'],
      dossier: +4,
      evidence: { kind: 'bribe', quality: 0.9, legal: false, label: "Enveloppe de Dédé au brigadier, vue de l’arrière-salle" },
    },
    witnessed: { exposure: 0.5, by: ['dede', 'ghislain', 'waiter', 'police'], effects: { risk: +40, setFlags: ['complaint_filed', 'backroom_caught'] } },
    result: "Entre deux fûts de bière, vous retenez votre souffle. Dédé tend une enveloppe et un waterzooi « offert ». Clic. Inutilisable au tribunal, inestimable dans un journal.",
  },
  {
    id: 'night_bribe_photo_window',
    label: 'Guetter le pot-de-vin depuis la fenêtre (point légal)',
    phase: 'night',
    legality: 'legal',
    cost: { minutes: 45 },
    requires: { flags: ['seen_complaisance'], notFlags: ['bribe_photo'], chance: 0.35 },
    effects: {
      setFlags: ['bribe_photo', 'corruption_proof'],
      dossier: +5,
      evidence: { kind: 'bribe', quality: 0.7, legal: true, label: "Repas offert et enveloppe à la patrouille, photographiés depuis la fenêtre" },
    },
    result: "Trois quarts d’heure à la fenêtre, et la voilà : l’assiette « offerte », l’enveloppe sous la serviette. Une photo prise de chez vous, sur la voie publique. Maître Vandamme va pleurer de joie.",
  },
  {
    id: 'night_eat_carbonnade_1',
    label: "Descendre manger une carbonnade à l’estaminet",
    phase: 'night',
    legality: 'legal',
    cost: { minutes: 60 },
    requires: { notFlags: ['carbonnade_1'] },
    effects: { setFlags: ['carbonnade_1'], sleep: +5, asso: -5, hostility: -10 },
    witnessed: { exposure: 0.9, by: ['klaas', 'seb_nico'], effects: { asso: -5 } },
    result: "Elle est bonne. C’est bien ça le pire : elle est vraiment bonne. Quelque part sur la place, un stylo gratte un carnet.",
  },
  {
    id: 'night_eat_carbonnade_2',
    label: "Redescendre manger une carbonnade (juste une)",
    phase: 'night',
    legality: 'legal',
    cost: { minutes: 60 },
    requires: { flags: ['carbonnade_1'], notFlags: ['carbonnade_2'] },
    effects: { setFlags: ['carbonnade_2'], sleep: +5, asso: -8, hostility: -15 },
    witnessed: { exposure: 0.9, by: ['klaas', 'seb_nico'], effects: { asso: -5 } },
    result: "Dédé vous appelle « min p’tit ». Vous ne protestez pas. Vous avez même pris le dessert.",
  },
  {
    id: 'night_eat_carbonnade_3',
    label: 'Prendre « la table de Pilou » à la terrasse',
    phase: 'night',
    legality: 'legal',
    cost: { minutes: 90 },
    requires: { flags: ['carbonnade_2'], notFlags: ['carbonnade_3'] },
    effects: { setFlags: ['carbonnade_3'], asso: -15, hostility: -30 },
    witnessed: { exposure: 1, by: ['klaas', 'seb_nico'], effects: { asso: -10 } },
    result: "Il est 23h40, vous êtes en terrasse, vous êtes sept à table. Vous êtes devenu ce que vous combattiez, et c’est plutôt confortable.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // APRÈS-MIDI — LÉGAL : institutions
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pm_report_mairie',
    label: 'Envoyer un signalement complet à la mairie',
    phase: 'afternoon',
    legality: 'legal',
    cost: { time: 1 },
    requires: { stats: { dossier: '>=5' } },
    effects: { setFlags: ['reported_mairie'], dossier: +1 },
    result: "Accusé de réception automatique : « Votre demande est importante pour nous. » Elle est importante pour eux comme le sont toutes les autres, c’est-à-dire en pile.",
  },
  {
    id: 'pm_email_inspector',
    label: "Écrire à l’inspectrice Delphine Vermeersch (dossier clim)",
    phase: 'afternoon',
    legality: 'legal',
    cost: { time: 1 },
    requires: { notFlags: ['emailed_inspector'] },
    effects: { setFlags: ['emailed_inspector'], dossier: +1 },
    result: "Réponse en 48 minutes, signée « D. Vermeersch ». Courtoise, précise, et vaguement inquiète de voir que vous travaillez chez Koddex.",
  },
  {
    id: 'pm_aot_request',
    label: "Demander le document AOT (le plan des zones de terrasse)",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { dossier: '>=3' } },
    effects: { setFlags: ['aot_requested', 'met_jeremie'], dossier: +1 },
    result: "Jérémie dépose la demande au nom de l’association, article et alinéa à l’appui. Accusé de réception automatique : « Votre demande sera traitée dans les meilleurs délais. » Jérémie note la date. Et l’heure.",
  },
  {
    id: 'pm_ars_complaint',
    label: "Saisir l’ARS et le service d’hygiène pour l’extraction",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { stats: { dossier: '>=8' } },
    effects: { setFlags: ['ars_complaint'], dossier: +2, hostility: +10 },
    result: "Formulaire de 9 pages, dont une sur « la nature olfactive de la nuisance ». Vous écrivez « frite rance, nuance carbonnade ». Le service d’hygiène programmera une visite. Un jour.",
  },
  {
    id: 'pm_hygiene_visit',
    label: "Relancer le service d’hygiène",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['ars_complaint'], day: [5, 13] },
    effects: { setFlags: ['hygiene_visit'], dossier: +2, hostility: +10 },
    result: "L’inspecteur d’hygiène est passé. Il a reniflé, noté, re-reniflé. Ghislain lui a promis que « c’est en cours ». Il l’a noté aussi.",
  },
  {
    id: 'pm_uritrottoir',
    label: 'Demander un uritrottoir pour la rue',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['saw_pee'] },
    effects: { setFlags: ['uritrottoir_requested'], asso: +3 },
    result: "Vous venez de demander officiellement une jardinière-pissotière à la Ville de Lille. Le formulaire propose trois coloris. La démocratie locale est une chose magnifique.",
  },
  {
    id: 'pm_uritrottoir_follow',
    label: "Relancer la demande d’uritrottoir",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['uritrottoir_requested', 'lescaut_meeting'] },
    effects: { setFlags: ['uritrottoir_installed'], asso: +5, hostility: +5 },
    result: "Il est là. Rouge, fleuri, devant le n°8. Les fêtards du samedi l’adorent. Votre porte, enfin, respire.",
  },
  {
    id: 'pm_request_lescaut',
    label: 'Demander un rendez-vous au maire, Bertrand Lescaut',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { asso: '>=30' } },
    effects: { setFlags: ['lescaut_requested'] },
    result: "Le cabinet du maire « prend bonne note ». Colette Verhaeghe, elle, prend son téléphone.",
  },
  {
    id: 'pm_meet_lescaut',
    label: "Rencontrer le maire à l’hôtel de ville",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { flags: ['lescaut_requested'], stats: { dossier: '>=15', asso: '>=40' } },
    effects: { setFlags: ['lescaut_meeting', 'met_lescaut'], dossier: +2, corruption: -5 },
    result: "Bertrand Lescaut a lu le dossier. Vraiment lu : il a des post-it. « La règle des 22h, c’est moi qui l’ai voulue. Elle sera appliquée. » Son conseiller, lui, regarde ses chaussures en pensant à Colette.",
  },
  {
    id: 'pm_lescaut_ally',
    label: 'Inviter le maire à une ronde du soir',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['lescaut_meeting'], stats: { asso: '>=50' } },
    effects: { setFlags: ['lescaut_ally'], corruption: -10, hostility: +15 },
    result: "Le maire a fait le tour avec Jérémie et Biloute. À 22h12, il a compté lui-même neuf personnes à une table. Biloute lui a fait pipi sur la chaussure. Ça crée des liens.",
  },
  {
    id: 'pm_inquiry_report',
    label: 'Transmettre la preuve de corruption aux autorités de contrôle',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { flags: ['corruption_proof'] },
    effects: { setFlags: ['inquiry_open'], corruption: -20, hostility: +20 },
    result: "Enquête interne ouverte. Le brigadier Lemaire découvre qu’un waterzooi peut coûter très cher. Les enquêteurs vous demanderont d’où vient chaque pièce, et à quelle heure. Préparez des réponses.",
  },
  {
    id: 'pm_lemaire_transfer',
    label: "Suivre l’enquête interne",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['inquiry_open', 'bribe_photo'] },
    effects: { setFlags: ['lemaire_transferred'], corruption: -20 },
    result: "Le brigadier Lemaire est muté à la surveillance des parcmètres de Lomme. On dit qu’il y mange moins bien.",
  },
  {
    id: 'pm_klaas_roster',
    label: 'Demander à Klaas de déduire le planning des patrouilles',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['called_police'] },
    effects: { setFlags: ['roster_known', 'met_klaas'] },
    result: "Klaas feuillette, compte, entoure. « Mardi et vendredi, c’est Lemaire. Ja. Même voiture, même heure, même lenteur. »",
  },

  // ════════════════════════════════════════════════════════════════════════
  // APRÈS-MIDI — LÉGAL : association
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pm_asso_meeting',
    label: "Réunir l’association",
    phase: 'afternoon',
    legality: 'legal',
    cost: { time: 2 },
    effects: { setFlags: ['asso_meeting', 'met_jeremie'], asso: +5, sleep: -3 },
    result: "Ordre du jour : un point. Durée : deux heures. Tatie a apporté un proverbe, Hilde une tarte au sucre, Seb un tableau Excel. Jérémie a tout consigné.",
  },
  {
    id: 'pm_hippolyte_room',
    label: "Demander à Hippolyte d’accueillir les réunions dans son atelier",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { asso: '>=20' } },
    effects: { setFlags: ['hippolyte_room', 'met_hippolyte'], asso: +8 },
    result: "L’ancienne carrosserie sent la cire et le XIXe siècle. On s’assied sous des roues de calèche. Les réunions durent toujours deux heures, mais avec plus de prestance.",
  },
  {
    id: 'pm_heritage',
    label: 'Saisir le patrimoine via Hippolyte (clim et gaine sur façade ancienne)',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['hippolyte_room'], stats: { dossier: '>=10' } },
    effects: { setFlags: ['heritage_angle'], dossier: +3, hostility: +5 },
    result: "Hippolyte a passé un coup de fil « à un vieil ami du service ». Une gaine inox sur une façade de 1729, ça, ça choque vraiment quelqu’un en ville.",
  },
  {
    id: 'pm_whatsapp_rally',
    label: `Mobiliser le groupe WhatsApp`,
    phase: 'afternoon',
    legality: 'legal',
    cost: { time: 1 },
    effects: { setFlags: ['whatsapp_rally', 'joined_whatsapp', 'met_seb_nico'], asso: +4 },
    result: "Seb poste un appel, Nico l’épingle. 42 messages en une heure, dont 11 sur l’ordre du jour et 31 sur Gaufre.",
  },
  {
    id: 'pm_petition_start',
    label: 'Lancer une pétition des riverains',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { asso: '>=20' } },
    effects: { setFlags: ['petition_started'], asso: +5, hostility: +5 },
    result: "« Pour le respect de la règle des 22h ». Première signature : Tatie, d’une écriture superbe. Deuxième : Klaas, horodatée.",
  },
  {
    id: 'pm_petition_deliver',
    label: 'Remettre la pétition à la mairie',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['petition_started'], stats: { asso: '>=35' } },
    effects: { setFlags: ['petition_delivered'], dossier: +3, asso: +5 },
    result: "Remise en main propre, tamponnée, photographiée. L’agente d’accueil vous dit qu’elle habite rue de Gand et qu’elle compatit.",
  },
  {
    id: 'pm_banners',
    label: 'Accrocher des banderoles « LE SOMMEIL EST UN DROIT » aux balcons',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { asso: '>=25' } },
    effects: { setFlags: ['banners_up'], asso: +6, hostility: +10 },
    result: "Six banderoles, dont une au balcon de Seb et Nico : Gaufre dort dessus. Les touristes les prennent en photo. Le bloc parle de « pollution visuelle ».",
  },
  {
    id: 'pm_recruit',
    label: 'Faire du porte-à-porte pour recruter des riverains',
    phase: 'afternoon',
    legality: 'legal',
    cost: { time: 2 },
    requires: { notFlags: ['recruited_residents'] },
    effects: { setFlags: ['recruited_residents'], asso: +10, sleep: -3 },
    result: "Quatre nouveaux membres, dont un couple qui croyait que l’association organisait la braderie. Ils restent quand même.",
  },
  {
    id: 'pm_tatie_emails',
    label: "Demander à Tatie de partager son fil d’e-mails « c’est en cours »",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['tatie_mail_3'] },
    effects: {
      setFlags: ['tatie_emails_shared', 'met_tatie'],
      dossier: +3,
      evidence: { kind: 'emails', quality: 0.7, legal: true, label: "Fil de Tatie : les promesses « c’est en cours », numérotées" },
    },
    result: "Tatie imprime tout, agrafe tout, et vous tend la liasse. « Si vous voulez quelque chose dans la vie, faut résister et se battre pour. Et garder ses e-mails. »",
  },

  // ════════════════════════════════════════════════════════════════════════
  // APRÈS-MIDI — LÉGAL : presse et avocat
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pm_press_contact',
    label: 'Contacter La Voix du Nordiste',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { dossier: '>=8' } },
    effects: { setFlags: ['press_contacted'] },
    result: "Anne-Sophie Lepoutre rappelle dans l’heure. « Des terrasses, de la clim sans permis ? Vous avez des photos ? »",
  },
  {
    id: 'pm_press_article',
    label: 'Donner une interview sur les terrasses',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { flags: ['press_contacted'], stats: { dossier: '>=15' } },
    effects: { setFlags: ['press_article'], asso: +8, hostility: +20, corruption: -5 },
    result: "Page 7 : « Rue des Bouchers, le sommeil en terrasse ». Photo de vous, fatigué, devant la gaine. Ghislain répond en encadré que « c’est en cours ».",
  },
  {
    id: 'pm_press_scandal',
    label: 'Donner la preuve de corruption à La Voix du Nordiste',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { flags: ['press_contacted', 'corruption_proof'] },
    effects: { setFlags: ['press_scandal'], corruption: -30, hostility: +30, asso: +5 },
    result: "Une : « WATERZOOI-GATE ». Les photos, les dates, les heures, les cafés. Colette Verhaeghe « ne commente pas ». Le téléphone de Dédé ne s’arrête plus.",
  },
  {
    id: 'pm_lawyer_hire',
    label: 'Mandater Maître Vandamme',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { stats: { asso: '>=25' } },
    effects: { setFlags: ['lawyer_hired'], asso: -3 },
    result: "Maître Vandamme facture à l’heure entamée et soupire à la minute. Il accepte. « La cotisation de l’association couvrira… le premier courrier. »",
  },
  {
    id: 'pm_formal_notice',
    label: "Envoyer une mise en demeure à l’estaminet",
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['lawyer_hired'], stats: { dossier: '>=12' } },
    effects: { setFlags: ['formal_notice'], dossier: +3, hostility: +20 },
    result: "Lettre recommandée avec accusé de réception. Ghislain a signé l’accusé. Réponse attendue sous quinze jours : vous pariez déjà qu’elle dira « c’est en cours ».",
  },

  // ════════════════════════════════════════════════════════════════════════
  // APRÈS-MIDI — GRIS
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pm_delphine_dinner',
    label: 'Accepter le dîner chez Stéphane (avec Delphine)',
    phase: 'afternoon',
    legality: 'grey',
    once: true,
    cost: { time: 3 },
    requires: { day: [3, 12] },
    effects: { setFlags: ['delphine_dinner', 'met_delphine'], job: +5, risk: +5 },
    result: "Stéphane parle de « vibes » entre l’entrée et le plat. Delphine parle de clim entre le plat et le dessert. Personne ne parle du conflit d’intérêts, c’est-à-dire de vous.",
  },
  {
    id: 'pm_delphine_channel',
    label: 'Glisser à Delphine que les visites annoncées ne servent à rien',
    phase: 'afternoon',
    legality: 'grey',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['delphine_dinner'], notFlags: ['inspector_announced', 'inspector_surprise'] },
    effects: { setFlags: ['delphine_channel'], corruption: -5, risk: +5 },
    witnessed: { exposure: 0.25, by: ['ghislain'], effects: { setFlags: ['conflict_exposed'], risk: +10 } },
    result: "Un SMS de Delphine : « Je verrai ce que je peux faire. Pas un mot à Stéphane. » La mairie vient de gagner un effet de surprise, et vous un secret.",
  },
  {
    id: 'pm_tatie_fake_leak',
    label: 'Pousser Tatie à « laisser fuiter » un faux plan à Colette',
    phase: 'afternoon',
    legality: 'grey',
    once: true,
    cost: { time: 1 },
    effects: { setFlags: ['tatie_fake_leak', 'met_tatie'], asso: -2 },
    result: "Tatie prend le thé chez Colette et évoque, l’air de rien, une « grande manif samedi ». Elle a adoré mentir. Elle en a fait un proverbe.",
  },
  {
    id: 'pm_bloc_fooled',
    label: 'Observer la réaction du bloc au faux plan',
    phase: 'afternoon',
    legality: 'grey',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['tatie_fake_leak', 'saturday1_done'], chance: 0.6 },
    effects: { setFlags: ['bloc_fooled'], hostility: -10, dossier: +2 },
    result: "Samedi, le bloc avait loué des barrières pour une manifestation qui n’a jamais existé. Dédé les a rangées lui-même. Et la preuve que Colette renseigne l’estaminet est désormais dans votre dossier.",
  },
  {
    id: 'pm_klaas_forget',
    label: 'Demander à Klaas de ne pas noter ce qu’il a vu',
    phase: 'afternoon',
    legality: 'grey',
    cost: { time: 1 },
    requires: { flags: ['klaas_noted_pilou'], notFlags: ['klaas_persuaded'] },
    effects: { setFlags: ['klaas_persuaded', 'met_hilde', 'met_klaas'], clearFlags: ['klaas_noted_pilou'], asso: -5, risk: -10 },
    result: "Hilde pose une main sur le carnet. Klaas soupire longuement. « Ja. Je n’ai pas regardé. » Il ne ment pas : il refuse de relire.",
  },
  {
    id: 'pm_klaas_lie',
    label: 'Mentir à Klaas (« ce n’était pas moi »)',
    phase: 'afternoon',
    legality: 'grey',
    cost: { time: 1 },
    requires: { flags: ['klaas_noted_pilou'], notFlags: ['klaas_lied_to'], chance: 0.5 },
    effects: { setFlags: ['klaas_lied_to'], clearFlags: ['klaas_noted_pilou'], risk: -5, asso: -8 },
    result: "Klaas raye la ligne. Proprement. Puis il en écrit une autre en dessous, que vous ne pouvez pas lire.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // APRÈS-MIDI — ILLÉGAL
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pm_fake_reviews',
    label: "Publier des faux avis sur l’estaminet",
    phase: 'afternoon',
    legality: 'illegal',
    cost: { time: 1 },
    requires: { flags: ['proj_fake_reviews'], notFlags: ['fake_reviews_traced'] },
    effects: { setFlags: ['fake_reviews'], hostility: +10, risk: +5 },
    witnessed: { exposure: 0.3, by: ['ghislain'], effects: { setFlags: ['fake_reviews_traced'], risk: +20, hostility: +15 } },
    result: "« Une étoile. Le serveur était aimable, mais le voisin du dessus avait l’air épuisé. » Douze comptes, douze styles, et les fautes d’orthographe, c’est vous qui les avez ajoutées. Clode Kode propose, à la place, « un avis sincère et nuancé sur la cuisson des frites ». Vous fermez l’onglet.",
  },
  {
    id: 'pm_read_reservations',
    label: 'Lire le cahier de réservations (sur leur réseau)',
    phase: 'afternoon',
    legality: 'illegal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['wifi_cracked'] },
    effects: {
      setFlags: ['read_reservations'],
      dossier: +2,
      evidence: { kind: 'reservations', quality: 0.7, legal: false, label: 'Réservations : jusqu’à 11 couverts par table, « terrasse jusqu’à 1h »' },
    },
    result: "Samedi, table 4 : « 11 pers., terrasse, NE PAS RENTRER avant 1h ». C’est écrit noir sur blanc, en Comic Sans.",
  },
  {
    id: 'pm_read_emails',
    label: 'Lire les e-mails « c’est en cours » côté estaminet',
    phase: 'afternoon',
    legality: 'illegal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['wifi_cracked'] },
    effects: {
      setFlags: ['read_emails'],
      dossier: +2,
      evidence: { kind: 'emails', quality: 0.7, legal: false, label: 'Brouillons de Ghislain : « répondre à la vieille que c’est en cours »' },
    },
    result: "Dossier « Brouillons » : un modèle de réponse nommé « TATIE_v7_final_FINAL.docx ». Ce n’est pas en cours. Ça n’a jamais été en cours.",
  },
  {
    id: 'pm_read_quotes',
    label: "Trouver les devis d’extraction jamais signés",
    phase: 'afternoon',
    legality: 'illegal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['wifi_cracked'] },
    effects: {
      setFlags: ['read_quotes'],
      dossier: +3,
      evidence: { kind: 'quotes', quality: 0.9, legal: false, label: 'Trois devis pour déplacer la gaine, jamais signés (2023–2025)' },
    },
    result: "Trois devis pour déplacer la gaine. Le moins cher coûte moins que la clim installée sans permis. Aucun n’est signé. Tous sont annotés « bof ».",
  },
  {
    id: 'pm_waiter_debrief',
    label: 'Retrouver le serveur en douce pour un débrief',
    phase: 'afternoon',
    legality: 'illegal',
    cost: { time: 1 },
    requires: { flags: ['waiter_bribed'], notFlags: ['waiter_fired', 'waiter_informant'] },
    effects: { setFlags: ['waiter_informant', 'seen_complaisance'], dossier: +2 },
    witnessed: { exposure: 0.2, by: ['dede'], effects: { setFlags: ['waiter_fired'], hostility: +10 } },
    result: "Au comptoir d’un café de la place, Théo parle bas : les jours où « le brigadier mange », les soirs où la cuisine ferme tôt, qui ment à qui. Il a l’air soulagé.",
  },
  // ── content-fixes : routes du scandal (README « Scandal proof ») ─────────
  {
    id: 'pm_waiter_testimony',
    label: 'Convaincre Théo de témoigner par écrit',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['waiter_informant'], notFlags: ['waiter_fired', 'waiter_testimony'] },
    effects: {
      setFlags: ['waiter_testimony', 'seen_complaisance', 'corruption_proof'],
      dossier: +4,
      evidence: { kind: 'testimony', quality: 0.75, legal: true, label: 'Attestation du serveur : repas offerts à la patrouille, coups de fil avant les passages' },
    },
    witnessed: { exposure: 0.3, by: ['dede'], effects: { setFlags: ['waiter_fired'], hostility: +10 } },
    result: "Théo relit trois fois, signe, et pose le stylo comme on pose une grenade. « Je fais que mon taf, moi. Mais mon taf, c’est pas de servir des cafés à la police pour qu’elle regarde ailleurs. » Maître Vandamme appellera ça « une pièce ». Théo appelle ça « ma démission, en avance ».",
  },
  {
    id: 'pm_klaas_notebook',
    label: 'Faire certifier les carnets de Klaas (tuyaux horodatés)',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 2 },
    requires: { flags: ['met_klaas', 'roster_known', 'seen_tipoff'], notFlags: ['klaas_log_certified'] },
    effects: {
      setFlags: ['klaas_log_certified', 'corruption_proof'],
      dossier: +4,
      evidence: { kind: 'notebook', quality: 0.8, legal: true, label: 'Carnets de Klaas : tables rentrées cinq minutes avant chaque patrouille, toujours les mêmes soirs' },
    },
    result: "Klaas recopie, date et signe chaque page : « Klaas, témoin, lunettes propres. » Jérémie tamponne au nom de l’association. Mis bout à bout, les tuyaux dessinent un horaire de bus : mêmes soirs, même voiture, cinq minutes d’avance. « Ja. Ce qui est régulier, on peut l’écrire. »",
  },
  {
    id: 'pm_answer_hate_wave',
    label: '« Bernadette harcelée » : répondre calmement, preuves à l’appui',
    phase: 'afternoon',
    legality: 'legal',
    once: true,
    cost: { time: 1 },
    requires: { flags: ['cm_fake_post'], notFlags: ['hate_wave_answered'] },
    effects: { setFlags: ['hate_wave_answered'], asso: +3 },
    result: "Pas d’insulte, pas de majuscules : trois photos horodatées, l’arrêté des 22h, et « Bernadette n’existe pas, mais nos nuits, si ». Nico relit, valide, publie. Les commentaires se calment. Un seul demande encore « vous fermez à quelle heure ? ». Vous répondez : 22h.",
  },
];
