// Registre des drapeaux (GAME_DESIGN §14). Tout drapeau utilisé dans src/content/* doit être déclaré ici.
// Valeur = description lisible (debug, linter, écran de fin).
// Les drapeaux de la section « posés par le moteur » sont attendus de la nuit 3D (src/sim) : voir README.md.
// Tous les autres sont posés par le contenu lui-même (effects.setFlags).

export const FLAGS = {
  // ── Posés par le moteur (nuit 3D / sim) ─────────────────────────────────
  night_photo: 'Pilou a pris au moins une photo de terrasse en infraction',
  night_db: 'Pilou a fait au moins un relevé en dB',
  corridor_measured: 'Pilou a mesuré un débordement sur le couloir de passage',
  called_police: 'Pilou a appelé la police municipale au moins une fois',
  called_as_asso: "Pilou a appelé « pour l'Association » (le bloc sait qui appelle)",
  seen_complaisance: 'Une visite « café offert, 0 PV » a été constatée',
  seen_tipoff: 'Un tuyau (tables rentrées juste avant la police) a été constaté',
  serial_caller: "Pilou est catalogué « c'est encore vous »",
  benali_fined: "L'agent Benali a verbalisé une terrasse",
  benali_transferred: "L'agent Benali a été muté pour excès de zèle",
  chief_came: 'Le chef de la police municipale est venu en personne',
  saw_pee: "Pilou a vu (ou photographié) quelqu'un uriner dans la rue",
  pee_at_door: "Quelqu'un a uriné contre la porte de Pilou",
  bucket_used: 'Pilou a vidé un seau d’eau par la fenêtre',
  bucket_witnessed: 'Le seau a été vu par quelqu’un',
  video_viral: 'Une vidéo de Pilou circule',
  klaas_noted_pilou: 'Klaas a noté un acte illégal de Pilou dans son carnet',
  talked_waiter: 'Pilou a parlé poliment au serveur la nuit',

  // ── Rencontres / début de partie ────────────────────────────────────────
  met_jeremie: 'Pilou a parlé à Jérémie',
  met_klaas: 'Pilou a parlé à Klaas',
  met_hilde: 'Pilou a parlé à Hilde',
  met_tatie: 'Pilou a parlé à Tatie Bouchon',
  met_seb_nico: 'Pilou a parlé à Seb et Nico',
  met_hippolyte: 'Pilou a rencontré Hippolyte',
  met_waiter: 'Pilou connaît le prénom du serveur (Théo)',
  met_delphine: 'Pilou a rencontré Delphine Vermeersch en personne',
  met_lescaut: 'Pilou a rencontré le maire Bertrand Lescaut',
  joined_whatsapp: 'Pilou est actif sur le groupe WhatsApp de l’association',
  joined_rounds: 'Pilou fait la ronde du soir avec Jérémie et Biloute',
  hilde_tisane: 'Hilde a apporté sa tisane à Pilou',
  roster_known: 'Klaas a déduit le planning des patrouilles de son carnet',
  legal_view: 'Pilou a obtenu le plan des zones (AOT) : vue légale débloquée',
  knows_trou: 'Pilou connaît le surnom historique de la rue, « le Trou »',

  // ── Événements fixes ────────────────────────────────────────────────────
  colette_dinner_seen: 'Pilou a vu Colette Verhaeghe dîner à l’estaminet (J4)',
  colette_dinner_photo: 'Pilou a photographié le dîner de Colette (J4)',
  colette_dinner_ignored: 'Pilou a ignoré le dîner de Colette (J4)',
  saturday1_done: 'Premier samedi sans voitures passé (J6)',
  saturday2_done: 'Second samedi sans voitures passé (J13)',
  ag_held: "L'assemblée générale a eu lieu (J7)",
  stance_legal: "Stratégie votée à l'AG : voie légale",
  stance_direct: "Stratégie votée à l'AG : « action directe »",
  stance_dialogue: "Stratégie votée à l'AG : dialogue avec les restaurateurs",
  inspector_announced: "La visite de l'inspectrice a été annoncée officiellement (J9)",
  inspector_surprise: "La visite de l'inspectrice a été une surprise (J9)",
  ac_violation_confirmed: 'Infraction confirmée sur la clim (J9)',
  ac_case_stalled: 'Le dossier de la clim s’enlise (J9)',
  exhaust_meeting_won: 'Réunion extraction (J11) : déplacement de la gaine acté',
  exhaust_meeting_delayed: 'Réunion extraction (J11) : « une étude complémentaire »',
  exhaust_meeting_lost: 'Réunion extraction (J11) : statu quo',
  commission_done: 'La commission des terrasses a statué (J14)',
  won_legal: 'Commission : AOT de l’estaminet suspendue, gaine déplacée',
  won_peace: 'Commission : charte de bon voisinage signée',
  won_scandal: 'Commission éclipsée par le scandale de corruption',
  commission_won: 'La commission a donné raison aux riverains (toutes victoires)',
  commission_lost: 'La commission a donné raison au bloc',

  // ── Actions légales ─────────────────────────────────────────────────────
  asked_waiter: 'Pilou a demandé poliment au serveur de rentrer les tables',
  reported_mairie: 'Signalement envoyé à la mairie',
  emailed_inspector: "E-mail envoyé à l'inspectrice",
  whatsapp_rally: 'Mobilisation sur le groupe WhatsApp',
  petition_started: 'Pétition des riverains lancée',
  petition_delivered: 'Pétition remise à la mairie',
  banners_up: 'Banderoles « LE SOMMEIL EST UN DROIT » aux balcons',
  press_contacted: 'La Voix du Nordiste a été contactée',
  press_article: 'Article publié dans La Voix du Nordiste',
  press_scandal: 'Article sur la corruption publié dans La Voix du Nordiste',
  lawyer_hired: 'Maître Vandamme est mandaté',
  formal_notice: 'Mise en demeure envoyée à l’estaminet',
  ars_complaint: "Plainte à l'ARS / à l'hygiène sur l'extraction",
  hygiene_visit: "Visite du service d'hygiène à l'estaminet",
  uritrottoir_requested: 'Uritrottoir demandé à la ville',
  uritrottoir_installed: 'Un uritrottoir trône désormais dans la rue',
  lescaut_requested: 'Rendez-vous demandé au maire',
  lescaut_meeting: 'Rendez-vous obtenu avec Bertrand Lescaut',
  lescaut_ally: 'Le maire soutient ouvertement les riverains',
  heritage_angle: "Hippolyte a saisi le service du patrimoine (clim et gaine en façade)",
  hippolyte_room: "L'association se réunit dans l'atelier d'Hippolyte",
  recruited_residents: 'De nouveaux riverains ont rejoint l’association',
  aot_requested: "Demande d'accès au document AOT déposée",
  tatie_emails_shared: "Tatie a partagé son fil d'e-mails « c'est en cours » avec l'association",

  // ── Actions grises ──────────────────────────────────────────────────────
  delphine_dinner: 'Dîner chez Stéphane avec Delphine (conflit d’intérêts)',
  delphine_channel: 'Canal informel ouvert avec Delphine',
  conflict_exposed: 'Le conflit d’intérêts du dîner est sorti',
  filmed_faces: 'Pilou a filmé des clients à visage découvert',
  police_flooded: 'Pilou a inondé la police d’appels',
  tatie_fake_leak: 'Tatie a fait fuiter un faux plan à Colette',
  bloc_fooled: 'Le bloc a mordu au faux plan',
  camera_window: 'Caméra à la fenêtre de Pilou (gris)',

  // ── Actions illégales ───────────────────────────────────────────────────
  camera_awning: 'Caméra cachée sous le store de l’estaminet',
  power_stolen: "Caméra branchée sur l'électricité de l'estaminet",
  wifi_cracked: "Wifi de l'estaminet craqué",
  read_reservations: 'Pilou a lu le cahier de réservations (preuve de surcapacité)',
  read_emails: 'Pilou a lu les e-mails « c’est en cours » côté estaminet',
  read_quotes: "Pilou a trouvé les devis d'extraction jamais signés",
  camera_found: 'La caméra cachée a été découverte',
  cardboard_exhaust: 'Carton scotché sur la sortie d’extraction',
  kitchen_fire: 'Début de feu dans la cuisine de l’estaminet',
  stink_bomb: "Boule puante lâchée sur la terrasse",
  fake_reviews: 'Faux avis publiés',
  fake_reviews_traced: 'Les faux avis ont été remontés jusqu’à Pilou',
  sabotage_chairs: 'Chaises dévissées',
  sabotage_parasols: 'Parasols volés',
  sabotage_locks: 'Cadenas de terrasse collés',
  waiter_bribed: 'Le serveur a été payé',
  waiter_informant: 'Le serveur renseigne Pilou',
  waiter_fired: 'Le serveur a été renvoyé',
  backroom_sneak: "Pilou s'est caché dans l'arrière-salle",
  bribe_photo: 'Enveloppe / repas offert à la police photographié depuis un point légal',
  bribe_photo_illegal: "Pot-de-vin photographié depuis l'arrière-salle (preuve illicite)",
  corruption_proof: 'Pilou détient une preuve de corruption police–bloc',
  igpn_open: "Enquête interne ouverte sur la police municipale",
  lemaire_transferred: 'Le brigadier Lemaire est muté',
  klaas_persuaded: 'Klaas a accepté de ne pas noter un acte de Pilou',
  klaas_lied_to: 'Pilou a menti à Klaas',
  complaint_filed: 'Plainte déposée contre Pilou',
  custody: 'Pilou a été placé en garde à vue',

  // ── Koddex ──────────────────────────────────────────────────────────────
  proj_db_logger: 'Démon Rust de relevé de décibels (preuve passive)',
  proj_whatsapp_bot: 'Bot WhatsApp de mobilisation',
  proj_scraper: "Scraper d'avis clients",
  scraper_boasts: 'Le scraper a trouvé des clients qui se vantent de la terrasse à 1h',
  proj_wifi_cracker: 'Craqueur de wifi (projet perso, très illégal à l’usage)',
  proj_fake_reviews: 'Générateur de faux avis',
  boss_noticed: 'Stéphane a remarqué la baisse de productivité',
  todo_app_rust: "L'appli de to-do de Stéphane a encore été réécrite en Rust",
  unemployed: 'Pilou a été licencié et se bat à plein temps',

  // ── Contre-offensives du bloc ───────────────────────────────────────────
  cm_bins: 'Poubelles devant la porte de Pilou',
  cm_smokers: 'Le personnel fume sous la fenêtre de Pilou',
  cm_table_dance: 'Tables rentrées à 21h59, ressorties à 22h20',
  cm_free_drinks: "Tournées offertes pour diviser l'association",
  tatie_wavering: 'Tatie Bouchon hésite, flattée par le bloc',
  cm_happy_petition: 'Pétition des « clients heureux »',
  cm_harassment_complaint: 'Plainte du bloc pour harcèlement',
  cm_defamation: 'Plainte du bloc pour diffamation',
  cm_colette_call: 'Le bloc a appelé Colette Verhaeghe',
  cm_festive_saturday: 'Lobbying pour un samedi « festif »',
  traitor_recruited: 'Le bloc a recruté un riverain (Régis)',
  traitor_known: 'Pilou sait que Régis renseigne le bloc',
  cm_fake_post: 'Faux post « Bernadette harcelée » → vague de haine',
  hate_wave_answered: "Pilou a répondu à la vague de haine sans l'alimenter",
  tatie_mail_1: 'Fil Tatie : promesse n°1 reçue',
  tatie_mail_2: 'Fil Tatie : promesse n°2 reçue',
  tatie_mail_3: 'Fil Tatie : promesse n°3 reçue',
  tatie_mail_4: 'Fil Tatie : promesse n°4 reçue',
  tatie_mail_5: 'Fil Tatie : promesse n°5 reçue',
  tatie_mail_6: 'Fil Tatie : promesse n°6 reçue',
  tatie_mail_7: 'Fil Tatie : promesse n°7 reçue (la dernière)',
  tatie_leaked_plan: 'Tatie a laissé fuiter un vrai plan à Colette',

  // ── Fins de partie ──────────────────────────────────────────────────────
  carbonnade_1: "Pilou a mangé la carbonnade de l'estaminet (1re fois)",
  carbonnade_2: "Pilou a remangé la carbonnade (2e fois)",
  carbonnade_3: 'Pilou est un habitué de l’estaminet',
  bombance_rumour: 'Rumeur : un bar veut ouvrir à La Bombance',
  bombance_bar_project: 'Projet de bar à La Bombance déposé',
  bombance_blocked: 'Projet de bar à La Bombance bloqué',
  random_drache: 'Une drache a vidé les terrasses',

  // ── content-actions (actions.js) ────────────────────────────────────────
  asso_meeting: "Pilou a réuni l'association un après-midi",
  kitchen_sabotaged: "Cuisine de l'estaminet sabotée (sel et sucre inversés)",
  laxative_done: 'Laxatif dans la carbonnade de l’estaminet',
  laxative_caught: 'Pilou identifié pour le laxatif',
  kitchen_sabotage_caught: 'Pilou identifié pour le sabotage de la cuisine',

  // ── content-koddex (koddex.js) ──────────────────────────────────────────
  proj_db_report: 'Relevés dB mis en forme pour la mairie (graphes + PDF)',
  proj_klaas_ocr: 'Carnet de Klaas numérisé (tableur horodaté)',

  // ── content-countermoves (countermoves.js) ──────────────────────────────
  tatie_mail_8: 'Fil Tatie : promesse n°8 reçue (la gaine de Roubaix)',
  tatie_mail_9: 'Fil Tatie : promesse n°9 reçue (patrimoine immatériel)',
  tatie_mail_10: 'Fil Tatie : promesse n°10 reçue (« c’est réparé »)',
  tatie_mail_11: 'Fil Tatie : promesse n°11 reçue (rédigée par Clode Kode)',
  tatie_mail_12: 'Fil Tatie : promesse n°12 reçue (réponse automatique)',
  regis_courted: "Un membre de l'association dîne gratis à l'estaminet (Klaas l'a noté)",
  regis_leak_petition: 'Le bloc a devancé la pétition grâce à une fuite',
  regis_leak_lawyer: "Le bloc a su pour l'avocat avant l'envoi",
  cm_regis_nuance: 'Régis démasqué propose une « médiation »',
  cm_counter_banner: 'Contre-banderole « ICI ON VIT, HEIN ! » sur la façade',
  cm_lawyer_reply: "L'avocat de l'estaminet a répondu à la mise en demeure",
  cm_air_freshener: 'Diffuseur « parfum frites fraîches » sous le store',
  cm_sugar_blame: 'Dédé a accusé la rue de Gand pour la carbonnade sucrée',
  cm_uritrottoir_terrace: "Dédé a annexé l'uritrottoir à sa terrasse",
};
