// Le fil du téléphone (contrat §14) : ce que Pilou lit entre deux phases. Données pures : aucune logique, aucun DOM.
// Trois fils : whatsapp (le groupe de l'association), press (La Voix du Nordiste), social (le bloc + les avis en ligne).
// Chaque entrée : { id, when, author, text, effects?, setFlags? } + champs facultatifs :
//   when     : conditions §14 (day, phase, flags, notFlags, stats, hidden, chance). Une entrée s'affiche une seule fois,
//              à la première lecture du fil où `when` correspond.
//   author   : un id de CHARACTERS (characters.js) ou de PLACES (le compte d'un commerce, ex. 'bernadette'),
//              ou 'reviewer' (un client anonyme, voir `handle`).
//   effects  : effets §14 appliqués à la lecture · setFlags : raccourci pour effects.setFlags
//   photo    : légende d'une photo jointe (whatsapp, social) · headline : titre (press)
//   handle   : pseudo affiché (social, author 'reviewer') · stars : note 1–5 (avis en ligne)
//   kind     : 'post' | 'review' | 'petition' (social)
//   ending   : id d'une fin (endings.js) : l'entrée n'apparaît que sur cet écran de fin, en « une » du journal.
// Règles : le nom du groupe vient de WHATSAPP_GROUP, jamais en dur. Anti-spoiler (README) : Régis n'est traître
// qu'après `traitor_known`, le serveur reste « le serveur » avant `met_waiter`, les repas offerts à la police
// n'existent qu'après `seen_complaisance`, le bar de La Bombance qu'après `bombance_rumour`.
// Fiction (§0) : personnages et commerces inventés, journal inventé.
import { WHATSAPP_GROUP } from './characters.js';

export const MEDIA = {
  // ════════════════════════════════════════════════════════════════════════
  // WHATSAPP : le groupe de l'association
  // ════════════════════════════════════════════════════════════════════════
  whatsapp: [
    // ── Le quotidien du groupe ──────────────────────────────────────────────
    {
      id: 'wa_welcome',
      when: { day: [1, 1] },
      author: 'seb',
      text: `Bienvenue à Pilou dans « ${WHATSAPP_GROUP} » 🎉 Règles du groupe : 1) on reste poli, 2) on horodate, 3) on ne parle pas de la carbonnade. Nico a ajouté la règle 3, je ne sais pas pourquoi.`,
    },
    {
      id: 'wa_welcome_nico',
      when: { day: [1, 1] },
      author: 'nico',
      text: "Règle 3 : parce qu’on a eu 200 messages sur la carbonnade en mars et zéro sur les décibels. Bienvenue, Pilou.",
    },
    {
      id: 'wa_jeremie_ag',
      when: { day: [1, 2] },
      author: 'jeremie',
      text: "Rappel : assemblée générale dimanche prochain. Ordre du jour : stratégie avant la commission. Merci de venir avec des photos datées et sans croissants (on avait dit « sans miettes sur le dossier »).",
    },
    {
      id: 'wa_jeremie_ag_eve',
      when: { day: [6, 6] },
      author: 'jeremie',
      text: "AG demain. Pensez à vos pièces : horodatage, distance, nombre de personnes par table. Une photo floue, c’est un souvenir.",
    },
    {
      id: 'wa_jeremie_commission_eve',
      when: { day: [13, 13] },
      author: 'jeremie',
      text: "Commission demain. Tenue correcte, dossier en trois exemplaires, personne ne dit « mafia » devant le maire. Je compte sur vous.",
    },
    {
      id: 'wa_cat_1',
      when: { day: [1, 3] },
      author: 'seb',
      photo: 'Gaufre au balcon, de profil, l’air de juger la terrasse',
      text: "Gaufre surveille la terrasse. Elle a compté 9 chaises à la table du fond. Elle n’a rien dit, mais elle a cligné lentement.",
    },
    {
      id: 'wa_cat_2',
      when: { day: [4, 8] },
      author: 'nico',
      photo: 'Gaufre endormie sur une pile de tracts',
      text: "La chatte a dormi sur les convocations de l’AG. On les a quand même distribuées. Elles sentent le chat. C’est plus militant.",
    },
    {
      id: 'wa_cat_3',
      when: { day: [9, 14] },
      author: 'seb',
      photo: 'Gaufre qui rentre, oreilles en arrière, à 23h40',
      text: "Gaufre est rentrée à 23h40, oreilles en arrière. Elle est plus rapide que la police municipale.",
    },
    {
      id: 'wa_tatie_proverb_1',
      when: { day: [1, 4] },
      author: 'tatie',
      text: "Si vous voulez quelque chose dans la vie, faut résister et se battre pour.",
    },
    {
      id: 'wa_tatie_proverb_2',
      when: { day: [5, 9] },
      author: 'tatie',
      text: "Petit à petit, l’oiseau fait son nid. Et la friture fait son trou. (Je cherche encore la fin.)",
    },
    {
      id: 'wa_tatie_proverb_3',
      when: { day: [10, 14] },
      author: 'tatie',
      text: "Qui dort dîne. Sauf rue des Bouchers : ici, c’est les autres qui dînent, et personne ne dort.",
    },
    {
      id: 'wa_tatie_wavering',
      when: { flags: ['tatie_wavering'] },
      author: 'tatie',
      text: "Il ne faut pas être trop dur avec ces jeunes gens. Dédé m’a offert un genièvre, il est très poli. Bon, c’est vrai que ça sent toujours. On peut être poli et sentir, remarquez.",
    },
    {
      id: 'wa_tatie_emails',
      when: { flags: ['tatie_emails_shared'] },
      author: 'tatie',
      text: "Je vous transfère tout le fil. Toutes les promesses. Classées. Avec les accusés de lecture. Faut résister, j’ai dit.",
      effects: { asso: +2 },
    },
    {
      id: 'wa_klaas_notebook_1',
      when: { day: [2, 4] },
      author: 'klaas',
      photo: 'Page du carnet de Klaas, écriture serrée, colonnes à la règle',
      text: "22h17 : 4 tables dehors. 22h31 : 3 tables. 22h48 : 4 tables. Une est revenue. Ja.",
    },
    {
      id: 'wa_klaas_notebook_2',
      when: { day: [7, 12] },
      author: 'klaas',
      photo: 'Page du carnet, une ligne soulignée deux fois',
      text: "Table 6 : 11 personnes. J’ai recompté. 11. Allee, 11 c’est pas 6.",
    },
    {
      id: 'wa_klaas_roster',
      when: { flags: ['roster_known'] },
      author: 'klaas',
      photo: 'Tableau à la main : jours, patrouilles, flèches',
      text: "Les patrouilles tournent. Je les ai mises en colonnes. Ce n’est pas de l’espionnage, c’est de la statistique.",
    },
    {
      id: 'wa_klaas_noted_pilou',
      when: { flags: ['klaas_noted_pilou'], notFlags: ['klaas_persuaded'] },
      author: 'klaas',
      text: "J’ai noté quelque chose cette nuit. Je ne dis pas quoi. Je dis seulement que je l’ai noté. Pilou sait.",
      effects: { asso: -2 },
    },
    {
      id: 'wa_hilde_soup',
      when: { day: [2, 5] },
      author: 'hilde',
      text: "J’ai fait trop de soupe. Je dis « trop », mais je l’ai faite exprès. Passez à la maison, il y a aussi de la tarte au sucre.",
    },
    {
      id: 'wa_hilde_tired',
      when: { stats: { sleep: '<30' } },
      author: 'hilde',
      text: "Pilou, vous avez une tête de lundi depuis jeudi. Je dépose une tisane devant votre porte. Ne répondez pas, dormez.",
      effects: { sleep: +3 },
    },
    {
      id: 'wa_hippolyte_room',
      when: { flags: ['hippolyte_room'] },
      author: 'hippolyte',
      text: "L’atelier de carrosserie est à votre disposition pour les réunions. Il y fait frais, ça sent le cuir et le vernis, et l’on n’y entend pas une seule chaise racler. Un luxe de 1827.",
    },
    {
      id: 'wa_hippolyte_heritage',
      when: { flags: ['heritage_angle'] },
      author: 'hippolyte',
      text: "J’ai déjeuné avec une vieille connaissance du service du patrimoine. Une gaine en inox sur une façade de 1729 l’a fait pâlir. Il ne pâlit jamais.",
    },
    {
      id: 'wa_regis_member',
      when: { day: [2, 6] },
      author: 'regis',
      text: "Bonjour à tous, Régis du 27. Je loue deux petits studios. Mes voyageurs adorent l’ambiance de la rue, mais je suis de tout cœur avec vous, bien sûr.",
    },
    {
      id: 'wa_regis_unmasked',
      when: { flags: ['traitor_public'] },
      author: 'nico',
      text: "Régis a quitté le groupe. Avant ça, il a fait 37 captures d’écran. J’ai vérifié. Moi aussi, je fais des captures.",
      effects: { asso: +3 },
    },

    // ── Réactions à la nuit de Pilou ────────────────────────────────────────
    {
      id: 'wa_first_photo',
      when: { flags: ['night_photo'] },
      author: 'jeremie',
      text: "Merci Pilou pour les photos. Horodatées, nettes, recevables. C’est le plus beau mot de la langue française.",
      effects: { asso: +1 },
    },
    {
      id: 'wa_police_called',
      when: { flags: ['called_police'] },
      author: 'seb',
      text: "Attends, attends : Pilou a appelé la police hier soir ?! Je veux tout. L’heure, le ton, ce que t’as dit. On en fait un feuilleton.",
    },
    {
      id: 'wa_serial_caller',
      when: { flags: ['serial_caller'] },
      author: 'nico',
      text: "Au standard, ils disent « c’est encore vous ». On est connus. Ce n’est pas forcément une bonne nouvelle.",
    },
    {
      id: 'wa_complaisance',
      when: { flags: ['seen_complaisance'] },
      author: 'seb',
      photo: 'Deux casquettes à une table de terrasse, deux cafés, zéro carnet à souches',
      text: "Ils sont venus, ils se sont assis, ils ont bu un café. Pas de PV. C’était une patrouille ou un brunch ?",
    },
    {
      id: 'wa_tipoff',
      when: { flags: ['seen_tipoff'] },
      author: 'klaas',
      text: "Hier soir : toutes les tables rentrées d’un coup, sans qu’un seul client soit parti. Cinq minutes plus tard : la police. « Tout est en ordre. » Un quart d’heure après : tables ressorties. Je n’interprète pas. Je note.",
    },
    {
      id: 'wa_benali',
      when: { flags: ['benali_fined'] },
      author: 'seb',
      text: "Un agent a mis un PV ! Un vrai ! Avec un stylo ! Je propose qu’on lui fasse une tarte. Hilde, tu valides ?",
    },
    {
      id: 'wa_benali_gone',
      when: { flags: ['benali_transferred'] },
      author: 'nico',
      text: "L’agent qui mettait des PV a été muté. Il était trop efficace. On note.",
      effects: { asso: -2 },
    },
    {
      id: 'wa_pee_door',
      when: { flags: ['pee_at_door'] },
      author: 'seb',
      text: "Pilou, désolé, mais quelqu’un a… ta porte… hier soir. Nico a la vidéo, je lui ai dit de ne PAS la partager.",
    },
    {
      id: 'wa_bucket',
      when: { flags: ['bucket_witnessed'] },
      author: 'nico',
      text: "Quelqu’un a vidé un seau sur la terrasse cette nuit. On ne sait pas qui. On sait d’où. Je rappelle la règle 1 du groupe.",
      effects: { asso: -2 },
    },
    {
      id: 'wa_bucket_hilde',
      when: { flags: ['bucket_witnessed'] },
      author: 'hilde',
      text: "L’eau, c’est pour la soupe.",
    },
    {
      id: 'wa_video',
      when: { flags: ['video_viral'] },
      author: 'seb',
      text: "Pilou. Il y a une vidéo. De toi. Elle tourne. Ma cousine de Tourcoing l’a vue. Ma cousine de Tourcoing ne voit RIEN d’habitude.",
    },
    {
      id: 'wa_stink_bomb',
      when: { flags: ['stink_bomb'] },
      author: 'tatie',
      text: "Cette nuit, ça sentait encore plus mauvais que d’habitude. Je ne savais pas que c’était possible. Il ne faut jamais dire jamais.",
    },
    {
      id: 'wa_cardboard',
      when: { flags: ['cardboard_exhaust'] },
      author: 'klaas',
      text: "Un carton sur la sortie d’extraction. Je n’ai pas vu qui. Je l’ai constaté ce matin, 7h10.",
    },
    {
      id: 'wa_sugar_rumour',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'seb',
      text: "Attends attends attends. Un client a craché sa carbonnade sur la terrasse en criant « C’EST SUCRÉ ». Je n’ai pas de vidéo. Je ne m’en remettrai jamais.",
    },
    {
      id: 'wa_sugar_nico',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'nico',
      text: "Règle 3, Seb.",
    },
    {
      id: 'wa_carbonnade_seen',
      when: { flags: ['carbonnade_1'] },
      author: 'klaas',
      text: "20h45 : un membre de l’association mange une carbonnade à l’estaminet. Je l’ai noté. Je note tout.",
      effects: { asso: -2 },
    },
    {
      id: 'wa_carbonnade_again',
      when: { flags: ['carbonnade_2'] },
      author: 'seb',
      text: "Pilou. Deux fois. DEUX carbonnades. On va devoir en parler à l’AG. Elle est bonne, au moins ?",
    },

    // ── Mobilisation et calendrier ──────────────────────────────────────────
    {
      id: 'wa_bot_live',
      when: { flags: ['proj_whatsapp_bot'] },
      author: 'nico',
      text: "Le bot est en ligne. Il s’appelle Bip. Il a dit bonjour à tout le monde, puis « il est 22h04, les terrasses ferment à 22h ». Tatie lui a répondu « merci, jeune homme ».",
    },
    {
      id: 'wa_bot_reminder',
      when: { flags: ['proj_whatsapp_bot'], day: [3, 14] },
      author: 'nico',
      text: "🤖 Bip : Rappel du soir. Terrasses fermées à 22h, 6 par table, le couloir reste libre. Bonne nuit (théorique) à tous.",
    },
    {
      id: 'wa_banners',
      when: { flags: ['banners_up'] },
      author: 'seb',
      photo: 'Trois balcons, trois draps peints : « LE SOMMEIL EST UN DROIT »',
      text: "Six banderoles, dont celle de Tatie, qui a une faute (« SOMEIL »). On la garde, c’est authentique.",
    },
    {
      id: 'wa_petition',
      when: { flags: ['petition_started'] },
      author: 'jeremie',
      text: "Pétition lancée. Signez avec votre vrai nom et votre vraie adresse : la mairie vérifie, contrairement à certaines autres pétitions.",
    },
    {
      id: 'wa_happy_petition',
      when: { flags: ['cm_happy_petition'] },
      author: 'nico',
      text: "Leur pétition des « clients heureux » : 2 300 signatures, dont une de Bruxelles nommée « Jean Bon ». J’ai fait une capture.",
    },
    {
      id: 'wa_saturday_1',
      when: { day: [6, 6] },
      author: 'seb',
      photo: 'La rue noire de monde, verres levés, une poussette coincée au milieu',
      text: "Samedi sans voitures. 18h et déjà une poussette coincée entre deux groupes debout. Elle a fini par passer. Le bébé a l’air épuisé, comme nous.",
    },
    {
      id: 'wa_saturday_2',
      when: { day: [13, 13] },
      author: 'klaas',
      text: "Deuxième samedi. J’ai rempli un carnet entier. J’en ai racheté trois. Hilde dit que je suis un client fidèle de la papeterie.",
    },
    {
      id: 'wa_colette_dinner',
      when: { flags: ['colette_dinner_photo'] },
      author: 'seb',
      text: "Les photos de Pilou du dîner de Colette Verhaeghe à l’estaminet ! Elle a eu un dessert. Personne d’autre n’a eu de dessert. Je dis ça.",
    },
    {
      id: 'wa_ag_legal',
      when: { flags: ['stance_legal'] },
      author: 'jeremie',
      text: "Merci à tous. L’AG a voté la voie légale. Je me sens comme un homme qui vient d’acheter un classeur neuf.",
      effects: { asso: +2 },
    },
    {
      id: 'wa_ag_direct',
      when: { flags: ['stance_direct'] },
      author: 'hilde',
      text: "L’AG a voté « action directe ». Je respecte le vote. Je ferai la soupe pour la garde à vue.",
    },
    {
      id: 'wa_ag_dialogue',
      when: { flags: ['stance_dialogue'] },
      author: 'tatie',
      text: "On a voté pour le dialogue. Très bien. Qui parle à qui ? Moi je parle à tout le monde, c’est mon problème d’ailleurs.",
    },
    {
      id: 'wa_inspector',
      when: { flags: ['ac_violation_confirmed'] },
      author: 'jeremie',
      text: "Infraction confirmée sur la clim. C’est écrit. Sur un papier. Avec un tampon. Je crois que je vais pleurer, mais avec dignité.",
      effects: { asso: +3 },
    },
    {
      id: 'wa_exhaust_won',
      when: { flags: ['exhaust_meeting_won'] },
      author: 'tatie',
      text: "La gaine va être déplacée ! Je l’avais dit : faut résister. Je vais envoyer un dernier e-mail à Ghislain. Pour le plaisir.",
    },
    {
      id: 'wa_exhaust_delayed',
      when: { flags: ['exhaust_meeting_delayed'] },
      author: 'nico',
      text: "Résultat de la réunion extraction : « une étude complémentaire ». J’ai lancé un compte à rebours. Il n’a pas de fin.",
    },
    {
      id: 'wa_uritrottoir',
      when: { flags: ['uritrottoir_installed'] },
      author: 'seb',
      photo: 'Un uritrottoir rouge tout neuf, une fleur plantée dessus',
      text: "Il est là. Il est rouge. Il a une fleur dessus. Je ne sais pas quoi ressentir.",
    },
    {
      id: 'wa_uritrottoir_annexed',
      when: { flags: ['cm_uritrottoir_terrace'] },
      author: 'klaas',
      text: "21h30 : une table de l’estaminet est installée à côté de l’uritrottoir. Ils l’ont mis sur la carte ?",
    },
    {
      id: 'wa_drache',
      when: { flags: ['random_drache'] },
      author: 'seb',
      text: "DRACHE ! Terrasse vidée en quatre minutes. La pluie a fait en un soir ce que la mairie n’a pas fait en deux ans.",
    },
    {
      id: 'wa_bombance',
      when: { flags: ['bombance_rumour'] },
      author: 'seb',
      text: "Attends, attends : il paraît qu’un bar veut ouvrir à La Bombance. UN BAR. Avec une licence de nuit. Je fais quoi, je panique ?",
    },
    {
      id: 'wa_bombance_nico',
      when: { flags: ['bombance_rumour'] },
      author: 'nico',
      text: "Tu ne paniques pas. Tu fais une capture.",
    },
    {
      id: 'wa_press_article',
      when: { flags: ['press_article'] },
      author: 'seb',
      photo: 'Capture de La Voix du Nordiste, page « Lille », un titre entouré au feutre',
      text: "ON EST DANS LE JOURNAL ! Page 7, entre un concours de pigeons et un nid-de-poule. C’est le plus beau jour du groupe.",
      effects: { asso: +3 },
    },
    {
      id: 'wa_hate_wave',
      when: { flags: ['cm_fake_post'] },
      author: 'nico',
      text: "Le post « Bernadette harcelée » a 4 000 partages. Personne ne répond, personne ne s’énerve, on garde les captures. Pilou, éteins ton téléphone.",
      effects: { sleep: -2 },
    },
    {
      id: 'wa_lescaut',
      when: { flags: ['lescaut_meeting'] },
      author: 'jeremie',
      text: "Le maire nous reçoit. Pas un adjoint. Le maire. J’ai repassé ma chemise deux fois.",
      effects: { asso: +2 },
    },
    {
      id: 'wa_custody',
      when: { flags: ['custody'] },
      author: 'hilde',
      text: "On m’a dit pour Pilou. J’ai fait une soupe. Est-ce qu’on peut apporter de la soupe en garde à vue ? Klaas, ne note pas ça.",
    },
    {
      id: 'wa_twist_van',
      when: { flags: ['twist_van_corridor'] },
      author: 'nico',
      text: "Pour le dossier : samedi, une camionnette de fûts garée deux heures dans le couloir, un jour « sans voitures ». J’ai la plaque, l’heure et une poussette qui fait demi-tour. Seb en a fait un montage en musique. Supprimé.",
    },
    {
      id: 'wa_twist_regis_party',
      when: { flags: ['twist_regis_party'] },
      author: 'seb',
      text: "Attends, attends : le bruit d’hier soir, c’était le 27. Le meublé de Régis. Dix-neuf étudiants, deux enceintes. Régis dit que c’était « un groupe calme ». Dans son annonce, « calme » est entre guillemets. J’ai vérifié.",
    },
    {
      id: 'wa_twist_fete_voisins',
      when: { flags: ['twist_fete_voisins'] },
      author: 'jeremie',
      text: "Merci à tous pour la fête des voisins. Rangée à 22h00 pile, comme prévu. Photo jointe de la place à 22h01, et de la terrasse de l’estaminet à 22h01. Je ne commente pas. Je joins.",
    },
    // ── content-unlocks : réactions aux twists de la nuit (twists.js, after.setFlags) ──
    {
      id: "wa_twist_colette",
      when: { flags: ['twist_colette_dinner'] },
      author: "seb",
      text: "Attends, attends : COLETTE VERHAEGHE à l’estaminet ce soir. Huit couverts sur une table de six. J’ai la photo, de loin, de travers, mais c’est elle.",
    },
    {
      id: "wa_twist_inspector",
      when: { flags: ['twist_inspector_seen'] },
      author: "nico",
      text: "La dame au carnet au Goulot hier soir, c’était l’inspectrice. Elle a pris des notes « en simple cliente ». Je l’aime bien.",
    },
    {
      id: "wa_twist_model_street",
      when: { flags: ['twist_model_street'] },
      author: "klaas",
      text: "Hier soir : six par table partout, tables rentrées à 21h58, géraniums neufs. J’ai noté « exceptionnel ». Puis j’ai noté « jusqu’à quand ? ».",
    },
    {
      id: "wa_twist_exhaust",
      when: { flags: ['twist_exhaust_silent'] },
      author: "tatie",
      text: "La gaine s’est éteinte la veille de la réunion. « Le loup se brosse les dents avant d’aller chez le dentiste. » Celle-là est de moi.",
    },
    {
      id: "wa_twist_birthday",
      when: { flags: ['twist_birthday'] },
      author: "seb",
      text: "Joyeux anniversaire Jojo 🎂 de la part de tout le deuxième étage. 23h40, onze voix, une seule note juste. Nico a enregistré : c’est pour le dossier.",
    },
    {
      id: "wa_twist_hen_party",
      when: { flags: ['twist_hen_party'] },
      author: "nico",
      text: "Le mégaphone de l’EVJF à 0h20 : 94 dB depuis notre balcon. Félicitations à Marion. Condoléances à nos oreilles.",
    },
    {
      id: "wa_twist_drache",
      when: { flags: ['twist_drache'] },
      author: "jeremie",
      text: "Point météo et légalité : hier, pendant la drache, quatorze personnes sur trois tables sous le store. Sec, oui. Six par table, non. C’est noté.",
    },
    {
      id: "wa_twist_heatwave",
      when: { flags: ['twist_heatwave'] },
      author: "hilde",
      text: "Avec cette chaleur, je fais de la citronnade pour tout le monde demain. Et des bouchons d’oreille : Klaas en achète par boîtes de cent.",
    },
    {
      id: "wa_twist_guide",
      when: { flags: ['twist_guide_tour'] },
      author: "hippolyte",
      text: "La balade nocturne a présenté notre rue comme « autrefois surnommée le Trou ». Autrefois. J’ai écrit à l’office de tourisme pour suggérer un adverbe plus exact.",
    },
    {
      id: "wa_twist_busker",
      when: { flags: ['twist_busker'] },
      author: "tatie",
      text: "L’accordéoniste a joué « Le P’tit Quinquin » trente-deux fois. J’ai compté. À la vingtième, j’ai chanté avec. Je ne m’en vante pas.",
    },
    {
      id: "wa_twist_power_cut",
      when: { flags: ['twist_power_cut'] },
      author: "klaas",
      text: "22h40 : panne. 23h25 : retour du courant. Entre les deux : bougies, étoiles, et 41 dB sous ma fenêtre. J’ai encadré la page.",
    },
    {
      id: "wa_twist_waiter",
      when: { flags: ['twist_waiter_holidays'] },
      author: "seb",
      text: "Le remplaçant du serveur rentre les tables à 23h passées. Je ne pensais pas écrire ça un jour : rendez-nous le serveur.",
    },
    {
      id: "wa_twist_lescaut",
      when: { flags: ['twist_lescaut_walk'] },
      author: "jeremie",
      text: "Le maire est passé hier à 23h : dix minutes exemplaires. Je lui ai envoyé ce matin les photos des dix minutes d’avant. Avec les heures.",
    },
    {
      id: "wa_twist_lost_dog",
      when: { flags: ['twist_lost_dog'] },
      author: "jeremie",
      text: "Merci à tous pour les recherches d’hier. Biloute va bien. Il était sous la table 3. Il a mangé des frites. Il ne regrette rien.",
    },
    {
      id: "wa_twist_sweeper",
      when: { flags: ['twist_street_sweeper'] },
      author: "nico",
      text: "La balayeuse de 23h30 a vidé les terrasses en quatre minutes. Je propose qu’on l’invite à l’AG. Seb propose qu’on l’adopte.",
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // PRESSE : La Voix du Nordiste
  // ════════════════════════════════════════════════════════════════════════
  press: [
    {
      id: 'press_rule_2200',
      when: { day: [1, 2] },
      author: 'journaliste',
      headline: 'Rue des Bouchers : 22h, l’heure du couvre-terrasse',
      text: "Rue des Bouchers, les terrasses ferment à 22h, contre 23h ou minuit ailleurs. « On n’est pas des citrouilles », proteste un patron. Un riverain : « Sur le papier. Sous ma fenêtre, la dernière chaise rentre à 0h40. »",
    },
    {
      id: 'press_trou',
      when: { day: [3, 5] },
      author: 'journaliste',
      headline: 'Patrimoine : le « Trou », une rue qui revient de loin',
      text: "Créée en 1729, la rue fut surnommée « le Trou » pour sa saleté. Un canal y coulait jusqu’en 1912 ; aujourd’hui, ce sont les pintes. « Une rue festive », assure un restaurateur. « Un trou », répond un riverain.",
      setFlags: ['knows_trou'],
    },
    {
      id: 'press_saturday_1',
      when: { flags: ['saturday1_done'] },
      author: 'journaliste',
      headline: 'Samedi sans voitures : la rue des Bouchers déborde',
      text: "Foule compacte, poussettes en slalom : le premier samedi piéton a fait le plein. Faute de sanitaires, certaines portes d’entrée ont servi de solution. Un habitant parle de « Fête de la musique sans musique ».",
    },
    {
      id: 'press_saturday_2',
      when: { flags: ['saturday2_done'] },
      author: 'journaliste',
      headline: 'Rebelote : deuxième samedi, deuxième débordement',
      text: "Même rue, même foule, même odeur. La police municipale a « fait des passages ». Combien ? « Des passages », répond la police municipale.",
    },
    {
      id: 'press_drache',
      when: { flags: ['random_drache'] },
      author: 'journaliste',
      headline: 'Météo : la drache, meilleure alliée des riverains ?',
      text: "Une averse soudaine a vidé les terrasses du Vieux-Lille en quelques minutes hier soir. « Le seul couvre-feu qui marche », sourit un habitant de la rue des Bouchers, avant de rentrer son linge.",
    },
    {
      id: 'press_residents',
      when: { flags: ['press_article'] },
      author: 'journaliste',
      headline: 'Rue des Bouchers : des riverains à bout de souffle',
      text: "Photos horodatées, décibels, carnet à la main : l’Association de la rue des Bouchers a monté un dossier. « On ne veut pas fermer les restaurants, on veut dormir », dit son président. L’estaminet : « tout est en cours ».",
    },
    {
      id: 'press_petition',
      when: { flags: ['petition_delivered'], notFlags: ['cm_happy_petition'] },
      author: 'journaliste',
      headline: 'Rue des Bouchers : les riverains pétitionnent',
      text: "Les riverains ont déposé leur pétition en mairie, signée presque entièrement par des habitants de la rue. « Ce ne sont que des voisins », relativise un restaurateur. C’est un peu le sujet.",
    },
    {
      id: 'press_petition_duel',
      when: { flags: ['petition_delivered', 'cm_happy_petition'] },
      author: 'journaliste',
      headline: 'Deux pétitions pour une rue',
      text: "Les riverains ont déposé leur pétition en mairie. Les restaurateurs aussi, avec dix fois plus de signatures, surtout hors de Lille. « La rue des Bouchers est aimée dans le monde entier », se félicite un restaurateur.",
    },
    {
      id: 'press_ac',
      when: { flags: ['ac_violation_confirmed'] },
      author: 'journaliste',
      headline: 'Clim sans autorisation : l’infraction est constatée',
      text: "L’inspectrice de la mairie a constaté qu’un groupe de climatisation avait été installé sans autorisation sur une façade de la rue des Bouchers. L’exploitant parle d’un « malentendu thermique ».",
    },
    {
      id: 'press_heritage',
      when: { flags: ['heritage_angle'] },
      author: 'journaliste',
      headline: 'Une gaine d’extraction sur une façade de 1729 ?',
      text: "Le service du patrimoine s’intéresse à une gaine en inox qui grimpe sur une façade ancienne de la rue des Bouchers. Les défenseurs du Vieux-Lille parlent de « verrue ». L’exploitant parle de « cheminée moderne ».",
    },
    {
      id: 'press_uritrottoir',
      when: { flags: ['uritrottoir_installed'] },
      author: 'journaliste',
      headline: 'Un uritrottoir rue des Bouchers : la ville s’engage',
      text: "Rouge, fleuri et inauguré sans discours : la ville a installé un uritrottoir rue des Bouchers. Les riverains se disent « soulagés ». Le mot a été choisi par eux.",
    },
    {
      id: 'press_scandal',
      when: { flags: ['press_scandal'] },
      author: 'journaliste',
      headline: 'Police municipale : cafés offerts et coups de fil, l’enquête',
      text: "Des riverains ont documenté des arrangements répétés entre un établissement de la rue et certaines patrouilles. La police municipale « prend ces allégations très au sérieux ». Le café, lui, reste offert.",
    },
    {
      id: 'press_inquiry',
      when: { flags: ['inquiry_open'] },
      author: 'journaliste',
      headline: 'Une enquête interne ouverte',
      text: "Des riverains ont transmis des documents : une enquête interne vise des agents municipaux. Le maire promet « la transparence totale ». L’ex-maire Colette Verhaeghe n’a « aucun commentaire, sauf que c’est scandaleux ».",
    },
    {
      id: 'press_lemaire',
      when: { flags: ['lemaire_transferred'] },
      author: 'journaliste',
      headline: 'Un brigadier muté après l’affaire des terrasses',
      text: "Le brigadier mis en cause dans l’affaire de la rue des Bouchers a été muté. Selon un collègue, il « aimait beaucoup la carbonnade, ce n’est pas un crime ». Personne n’a dit que c’en était un.",
    },
    {
      id: 'press_sugar',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'journaliste',
      headline: 'Vieux-Lille : mystère sucré dans une cuisine',
      text: "Frites au sucre glace, crème brûlée salée : un estaminet de la rue des Bouchers a servi un soir une carte « inversée ». La direction évoque « un fournisseur de la rue de Gand ». La rue de Gand dément.",
    },
    {
      id: 'press_hate_wave',
      when: { flags: ['cm_fake_post'] },
      author: 'journaliste',
      headline: 'Réseaux sociaux : « Bernadette » harcelée ? Il n’y a pas de Bernadette',
      text: "Un post viral dénonce le harcèlement d’un estaminet par « un riverain ». Petite précision : Bernadette n’existe pas, c’est un nom d’enseigne. Le riverain, lui, existe, et il aimerait bien dormir.",
    },
    {
      id: 'press_bombance',
      when: { flags: ['bombance_bar_project'] },
      author: 'journaliste',
      headline: 'La Bombance : un bar de nuit dans les cartons',
      text: "Le local vide de La Bombance pourrait accueillir un bar à cocktails ouvert « jusqu’à tard ». Le porteur de projet promet « une ambiance feutrée ». Les riverains ont acheté des bouchons d’oreille feutrés.",
    },
    {
      id: 'press_commission_eve',
      when: { day: [13, 13] },
      author: 'journaliste',
      headline: 'Terrasses : la commission tranche dimanche',
      text: "Riverains et restaurateurs de la rue des Bouchers sont attendus demain en mairie. D’un côté, des classeurs. De l’autre, des chaises. Le maire promet « d’écouter tout le monde ». Tout le monde compte parler.",
    },

    // ── Les « unes » des fins (une par fin) ─────────────────────────────────
    {
      id: 'press_end_legal',
      when: { flags: ['won_legal', 'exhaust_meeting_won'] },
      ending: 'legal_victory',
      author: 'journaliste',
      headline: 'Rue des Bouchers : la commission donne raison aux riverains',
      text: "Autorisation de terrasse suspendue, gaine d’extraction déplacée : le dossier de l’Association a convaincu. « Horodaté, mesuré, recevable », résume son président, ému. Un restaurateur va « faire appel à la rue de Gand ».",
    },
    {
      id: 'press_end_legal_ac',
      when: { flags: ['won_legal'], notFlags: ['exhaust_meeting_won'] },
      ending: 'legal_victory',
      author: 'journaliste',
      headline: 'Rue des Bouchers : la commission donne raison aux riverains',
      text: "Autorisation de terrasse suspendue : le dossier de l’Association a convaincu. La gaine d’extraction, elle, attend toujours son étude. « Une victoire, pas une fin », résume son président, ému. Un restaurateur va « faire appel à la rue de Gand ».",
    },
    {
      id: 'press_end_peace',
      when: { flags: ['won_peace'] },
      ending: 'negotiated_peace',
      author: 'journaliste',
      headline: 'Une charte de bon voisinage signée rue des Bouchers',
      text: "Tables rentrées à 22h, couloir dégagé, une réunion par trimestre : riverains et restaurateurs ont signé une charte. Sur la photo, tout le monde sourit. Un peu trop, selon un habitant au carnet.",
    },
    {
      id: 'press_end_scandal',
      when: { flags: ['won_scandal'] },
      ending: 'scandal',
      author: 'journaliste',
      headline: 'Terrasses, cafés offerts et coups de fil : la rue des Bouchers fait trembler la mairie',
      text: "La commission des terrasses a été éclipsée par l’affaire de corruption. Les terrasses ferment à 22h. Les cafés offerts, eux, ont fermé tout court. Notre enquête continue.",
    },
    {
      id: 'press_end_custody',
      when: { flags: ['custody'] },
      ending: 'custody',
      author: 'journaliste',
      headline: 'Un riverain en garde à vue : la guerre des terrasses dérape',
      text: "Un habitant de la rue des Bouchers a été placé en garde à vue. Les restaurateurs se disent « choqués ». L’association se dit « choquée aussi, mais pas pour les mêmes raisons ». Une voisine a apporté de la soupe.",
    },
    {
      id: 'press_end_custody_sugar',
      when: { flags: ['custody', 'kitchen_sabotage_caught'], notFlags: ['laxative_caught'] },
      ending: 'custody',
      author: 'journaliste',
      headline: 'L’affaire de la « carbonnade sucrée » devant la justice',
      text: "Le sel et le sucre avaient été inversés dans la cuisine d’un estaminet : le suspect est un voisin. Aucun client n’a été blessé, mais plusieurs ont « perdu foi en la frite ». L’audience promet d’être croustillante.",
    },
    {
      id: 'press_end_custody_laxative',
      when: { flags: ['custody', 'laxative_caught'] },
      ending: 'custody',
      author: 'journaliste',
      headline: 'Carbonnade laxative : un riverain devant le tribunal correctionnel',
      text: "Quatorze clients d’un estaminet de la rue des Bouchers sont tombés malades après un repas. Le suspect est un voisin. Personne, cette fois, ne parle de convivialité.",
    },
    {
      id: 'press_end_moving',
      when: {},
      ending: 'moving_out',
      author: 'journaliste',
      headline: 'Wazemmes accueille un nouveau riverain (fatigué)',
      text: "Un développeur quitte la rue des Bouchers pour Wazemmes. « Il y a le marché le dimanche matin, mais au moins il s’arrête », confie-t-il. Son ancien appartement est déjà loué. En location saisonnière.",
    },
    {
      id: 'press_end_fired',
      when: {},
      ending: 'fired',
      author: 'journaliste',
      headline: 'Start-up lilloise : « on est une famille, mais on ship »',
      text: "Portrait de Koddex, start-up du Vieux-Lille. Son fondateur évoque « une transition dans l’équipe » : l’équipe comptait une personne. L’assistant de code reste en poste et « adresse ses meilleurs vœux » au partant.",
    },
    {
      id: 'press_end_turncoat',
      when: { flags: ['carbonnade_3'] },
      ending: 'turncoat',
      author: 'journaliste',
      headline: 'Rue des Bouchers : l’ancien militant devenu habitué',
      text: "Il photographiait la terrasse. Il y dîne désormais trois fois par semaine. « La carbonnade est excellente », assure-t-il. Un voisin barbu a été vu en train de prendre note.",
    },
    {
      id: 'press_end_return',
      when: { flags: ['bombance_bar_project'] },
      ending: 'the_return',
      author: 'journaliste',
      headline: 'La Bombance rouvre : la rue des Bouchers retient son souffle',
      text: "À peine la commission passée, un bar de nuit ouvre ses portes au n°4. Son gérant promet « de la musique douce ». La première nuit, la musique douce s’entendait depuis la place Maurice-Schumann.",
    },
    {
      id: 'press_twist_match',
      when: { flags: ['twist_match_night'] },
      author: 'journaliste',
      headline: "Écran géant rue des Bouchers : 150 supporters et une rue saturée",
      text: "Pour la victoire de Lille, un estaminet du Vieux-Lille avait tourné un écran géant vers la rue. Ambiance « de folie », selon les supporters. « De folie », confirment les riverains.",
    },
    {
      id: 'press_twist_fire',
      when: { flags: ['twist_fire_inspection'] },
      author: 'journaliste',
      headline: "Vieux-Lille : les pompiers mesurent les couloirs de passage",
      text: "Lors d’un exercice nocturne, les sapeurs-pompiers ont relevé un passage de 1,40 m rue des Bouchers, pour 2 m exigés. Un restaurateur évoque « un malentendu sur le mobilier ».",
    },
    {
      id: 'press_twist_tv',
      when: { flags: ['twist_tv_crew'] },
      author: 'journaliste',
      headline: "« Les pépites du Vieux-Lille » : un estaminet à l’honneur",
      text: "Le reportage diffusé hier montre une terrasse impeccable. Plusieurs riverains ont fait parvenir à la rédaction des photos prises le même soir, une demi-heure plus tard. La rédaction remercie les riverains.",
    },
    // ── content-unlocks : réactions aux twists de la nuit (twists.js, after.setFlags) ──
    {
      id: "press_twist_colette",
      when: { flags: ['twist_colette_dinner'] },
      author: "journaliste",
      headline: "L’ancienne maire dîne en terrasse rue des Bouchers",
      text: "Colette Verhaeghe a été aperçue jeudi soir à la terrasse d’un estaminet de la rue des Bouchers, à une table de huit couverts. Le maximum y est de six. « Je dînais entre amis », a-t-elle précisé. Huit amis.",
    },
    {
      id: "press_twist_power",
      when: { flags: ['twist_power_cut'] },
      author: "journaliste",
      headline: "Panne de courant dans le Vieux-Lille : 45 minutes d’obscurité",
      text: "Lampadaires éteints, terrasses aux bougies : rue des Bouchers, des riverains parlent de « la nuit la plus calme de l’année ». Le gestionnaire du réseau évoque un incident technique.",
    },
    {
      id: "press_twist_sweeper",
      when: { flags: ['twist_street_sweeper'] },
      author: "journaliste",
      headline: "Nettoyage de nuit : la balayeuse fait rentrer les terrasses",
      text: "Nouveaux horaires de nettoyage dans le Vieux-Lille : la balayeuse-laveuse passe à 23h30 rue des Bouchers. Les restaurateurs n’avaient pas lu l’affichette. « On a été prévenus par un lampadaire », regrette l’un d’eux.",
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // RÉSEAUX : les comptes du bloc et les avis en ligne
  // ════════════════════════════════════════════════════════════════════════
  social: [
    // ── Les posts du bloc ───────────────────────────────────────────────────
    {
      id: 'so_promo_terrace',
      when: { day: [1, 3] },
      author: 'bernadette',
      kind: 'post',
      photo: 'Terrasse illuminée, guirlandes, verres de bière dorée',
      text: "Ce soir, terrasse ouverte « jusqu’à pas d’heure » 🍻 Waterzooi, carbonnade et bonne humeur ! #VieuxLille #ChtiVibes",
    },
    {
      id: 'so_promo_2200',
      when: { day: [4, 8] },
      author: 'bernadette',
      kind: 'post',
      text: "Petit rappel : notre terrasse ferme à 22h. 😉 La salle, elle, reste ouverte, et les fenêtres aussi. Venez nombreux !",
    },
    {
      id: 'so_promo_happy_hour',
      when: { day: [5, 12] },
      author: 'malunes',
      kind: 'post',
      text: "Happy hour 21h–23h en terrasse 🥩🍷 « Une heure heureuse dure parfois deux heures », comme dit le patron.",
    },
    {
      id: 'so_rue_de_gand',
      when: { day: [2, 9] },
      author: 'bernadette',
      kind: 'post',
      text: "Rue de Gand : minuit. Rue des Bouchers : 22h. Cherchez l’erreur. 🤔 Partagez si vous aimez la convivialité !",
    },
    {
      id: 'so_bloemkool',
      when: { day: [3, 10] },
      author: 'bloemkool',
      kind: 'post',
      photo: 'Assiette minimaliste : trois carottes, une émulsion, une fleur',
      text: "Nouvelle carte d’été. Chou-fleur rôti, beurre noisette, silence relatif. Nous fermons notre terrasse à 22h, comme il se doit. (Nous soutenons nos voisins. Globalement.)",
    },
    {
      id: 'so_mug',
      when: { day: [6, 6] },
      author: 'mug',
      kind: 'post',
      text: "Samedi sans voitures = samedi sans limites 🥤 Emportez votre verre, la rue est à vous !",
    },
    {
      id: 'so_happy_petition',
      when: { flags: ['cm_happy_petition'] },
      author: 'bernadette',
      kind: 'petition',
      text: "📝 Pétition « Pour une rue des Bouchers VIVANTE » : 2 300 signatures ! Merci à nos clients de Lille, de Bruxelles et de Lisbonne ❤️ Une rue qui dort est une rue qui meurt.",
    },
    {
      id: 'so_fake_post',
      when: { flags: ['cm_fake_post'] },
      author: 'bernadette',
      kind: 'post',
      text: "💔 Depuis des semaines, notre petite équipe est HARCELÉE par UN riverain : photos, appels, plaintes. Nous voulons juste faire vivre le Vieux-Lille. Soutenez Bernadette ❤️ #JeSuisBernadette",
      effects: { sleep: -3 },
    },
    {
      id: 'so_fake_post_comments',
      when: { flags: ['cm_fake_post'] },
      author: 'reviewer',
      handle: 'Ludo_Roubaix',
      kind: 'post',
      text: "Courage Bernadette !! Les gens qui veulent du calme, qu’ils aillent à la campagne 😡 (Vous fermez à quelle heure ?)",
    },
    {
      id: 'so_free_drinks',
      when: { flags: ['cm_free_drinks'] },
      author: 'bernadette',
      kind: 'post',
      text: "Ce soir, la tournée est offerte aux VOISINS 🍺 Parce qu’on s’aime, dans cette rue. (Sur présentation d’un justificatif de domicile.)",
    },
    {
      id: 'so_counter_banner',
      when: { flags: ['cm_counter_banner'] },
      author: 'bernadette',
      kind: 'post',
      photo: 'Banderole « ICI ON VIT, HEIN ! » sur la façade de l’estaminet',
      text: "Notre réponse aux banderoles d’en face. Ici, on vit, hein ! Et on vit jusqu’à 22h, bien sûr. 😇",
    },
    {
      id: 'so_air_freshener',
      when: { flags: ['cm_air_freshener'] },
      author: 'bernadette',
      kind: 'post',
      text: "Nouveau : un diffuseur « frites fraîches » sous notre store 🍟 Parce que l’odeur, c’est aussi de la convivialité.",
    },
    {
      id: 'so_sugar_blame',
      when: { flags: ['cm_sugar_blame'] },
      author: 'bernadette',
      kind: 'post',
      text: "Suite à un incident avec un fournisseur (rue de Gand, on ne dit pas qui), notre carbonnade a été « surprenante » hier soir. Tout est rentré dans l’ordre. C’est en cours de résolution. 🙏",
    },
    {
      id: 'so_lescaut_attack',
      when: { flags: ['lescaut_ally'] },
      author: 'colette',
      kind: 'post',
      text: "De mon temps, on savait que Lille vivait la nuit. Certains préfèrent une ville-dortoir. Je ne citerai personne. (Bertrand.)",
    },
    {
      id: 'so_end_return',
      when: { flags: ['bombance_bar_project'] },
      ending: 'the_return',
      author: 'bombance',
      kind: 'post',
      text: "🍸 GRANDE OUVERTURE ce vendredi ! Cocktails, DJ, et notre petite cour pour fumer « en toute discrétion ». Ouvert jusqu’à 2h. À très vite, voisins !",
    },

    // ── Les avis en ligne ───────────────────────────────────────────────────
    {
      id: 'rv_boast_1',
      when: { day: [1, 5] },
      author: 'reviewer',
      handle: 'Kévin59',
      kind: 'review',
      stars: 5,
      text: "Terrasse jusqu’à 1h, ambiance de folie !!! On était 11 sur une table de 6 et personne n’a rien dit 🍻 Le voisin du 2e a crié, trop drôle 😂",
    },
    {
      id: 'rv_boast_2',
      when: { day: [3, 9] },
      author: 'reviewer',
      handle: 'MarieLouise_B',
      kind: 'review',
      stars: 5,
      text: "Le meilleur mardi de ma vie. Le serveur nous a dit que la terrasse fermait à 22h, mais on est restés jusqu’à minuit, il était trop gentil. 10/10.",
    },
    {
      id: 'rv_boast_3',
      when: { day: [6, 14] },
      author: 'reviewer',
      handle: 'Thibault.EVG',
      kind: 'review',
      stars: 4,
      text: "Enterrement de vie de garçon top ! On a chanté jusqu’à 1h devant l’estaminet. -1 étoile parce qu’un vieux monsieur barbu, tout au bout de la rue, nous regardait en écrivant dans un carnet. Flippant.",
    },
    {
      id: 'rv_carbonnade_good',
      when: { day: [1, 14], notFlags: ['kitchen_sabotaged'] },
      author: 'reviewer',
      handle: 'Gourmet_du_Nord',
      kind: 'review',
      stars: 4,
      text: "Carbonnade généreuse, frites croustillantes, un peu bruyant en terrasse. Des voisins nous regardaient depuis leurs fenêtres, c’était folklorique.",
    },
    {
      id: 'rv_smell',
      when: { day: [2, 14] },
      author: 'reviewer',
      handle: 'Odile_V',
      kind: 'review',
      stars: 2,
      text: "Bonne cuisine, mais l’odeur de friture monte dans toute la rue. J’habite au milieu de la rue. On me répond toujours que c’est en cours. Faut résister.",
    },
    {
      id: 'rv_sugar_1',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'reviewer',
      handle: 'Julien_Lambersart',
      kind: 'review',
      stars: 1,
      text: "Carbonnade SUCRÉE. Pas « un peu sucrée comme d’habitude » : sucrée comme un dessert. Les frites avaient du sucre glace. J’ai cru à un concept.",
    },
    {
      id: 'rv_sugar_2',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'reviewer',
      handle: 'Anaïs.Croix',
      kind: 'review',
      stars: 1,
      text: "Crème brûlée salée. Je ne suis pas contre l’innovation, mais prévenez. Le patron a accusé la rue de Gand. La rue de Gand n’était pas là.",
    },
    {
      id: 'rv_sugar_3',
      when: { flags: ['kitchen_sabotaged'] },
      author: 'reviewer',
      handle: 'Bruno_Waterzooi',
      kind: 'review',
      stars: 5,
      text: "La carbonnade au goût de pain d’épices, c’est exactement comme chez ma grand-mère. Enfin un estaminet authentique !! Ne changez rien.",
    },
    {
      id: 'rv_fake_suspect',
      when: { flags: ['fake_reviews'] },
      author: 'reviewer',
      handle: 'Un_client_lambda_12',
      kind: 'review',
      stars: 1,
      text: "Une étoile. Le serveur était aimable, mais le voisin du dessus avait l’air épuisé, ce qui gâche l’ambiance. Et les dB étaient trop hauts. Je suis un client normal.",
    },
    {
      id: 'rv_fake_reply',
      when: { flags: ['fake_reviews_traced'] },
      author: 'ghislain',
      kind: 'review',
      text: "Réponse du propriétaire : « Merci pour vos douze avis, cher voisin. Ils ont tous la même faute d’accord. Notre avocat vous écrira. C’est en cours. »",
      effects: { risk: +3 },
    },
    {
      id: 'rv_owner_reply',
      when: { day: [4, 14] },
      author: 'ghislain',
      kind: 'review',
      text: "Réponse du propriétaire à un avis 2 étoiles : « Chère cliente, nous avons bien pris en compte votre remarque. C’est en cours de résolution. Bien cordialement. »",
    },
    {
      id: 'rv_stink',
      when: { flags: ['stink_bomb'] },
      author: 'reviewer',
      handle: 'Pauline_Wazemmes',
      kind: 'review',
      stars: 1,
      text: "Odeur d’œuf pourri sur la terrasse vers 23h. Le patron dit que c’est le canal d’avant 1912. Je n’ai pas compris, j’ai payé quand même.",
    },
    {
      id: 'rv_drache',
      when: { flags: ['random_drache'] },
      author: 'reviewer',
      handle: 'Steph_Tourisme',
      kind: 'review',
      stars: 3,
      text: "Drache à 21h, tout le monde à l’intérieur. Bizarrement, c’était super calme et la carbonnade était meilleure. Bonne soirée, mais je crois que les voisins ont applaudi.",
    },
    {
      id: 'rv_tourist',
      when: { day: [8, 14] },
      author: 'reviewer',
      handle: 'Jan_from_Gent',
      kind: 'review',
      stars: 5,
      text: "Very authentic street, very nice beer, very angry man at the window at midnight. 5 stars, would shout again.",
    },
    {
      id: 'rv_turncoat',
      when: { flags: ['carbonnade_3'] },
      author: 'reviewer',
      handle: 'Pilou_du_10',
      kind: 'review',
      stars: 4,
      text: "Je dois l’admettre : la carbonnade est très bonne. -1 étoile pour la gaine d’extraction. Je sais de quoi je parle.",
    },
    {
      id: 'so_twist_influencer',
      when: { flags: ['twist_influencer'] },
      author: 'reviewer',
      handle: 'Lou.lillestyle',
      kind: 'post',
      text: "La vraie nuit lilloise ✨ Ambiance, guirlandes, gens trop chaleureux 🥰 (et un monsieur qui m’a fait coucou du deuxième étage, trop mignon) #VieuxLille #Authentique",
    },
    // ── content-unlocks : réactions aux twists de la nuit (twists.js, after.setFlags) ──
    {
      id: "so_twist_birthday",
      when: { flags: ['twist_birthday'] },
      author: "reviewer",
      handle: "Jojo_40ans",
      kind: "post",
      text: "Meilleur anniversaire de ma vie à l’estaminet 🎉 Merci à toute la rue d’avoir chanté avec nous (les voisins aussi je crois ??) #40ans #VieuxLille",
    },
    {
      id: "so_twist_hen_party",
      when: { flags: ['twist_hen_party'] },
      author: "reviewer",
      handle: "temoin.de.marion",
      kind: "post",
      text: "EVJF de rêve aux Bouchers Mal Lunés 👰💕 Le mégaphone a été un SUCCÈS. On a même eu des applaudissements d’une fenêtre. Ou c’était des volets.",
    },
    {
      id: "so_twist_heatwave",
      when: { flags: ['twist_heatwave'] },
      author: "bernadette",
      kind: "post",
      text: "Canicule 🥵 Notre terrasse reste ouverte pour vous rafraîchir ! Jusqu’à 22h, bien sûr 😇 #Convivialité #Lille",
    },
  ],
};
